### ISSUE TITLE
Rending issues on Microsoft Edge

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#1]
There are several rendering issues when using Microsoft Edge.

Tested with Windows 10 (10.0.17763.134), Edge version 44.17763.1.0

1. Tab layout
2. Scroll bars on the install commands 
3. Scroll bars in the documentation nav
4. Scroll bars in the documentation FastPath

See attachments

<img width="389" alt="screen shot 2018-11-21 at 8 25 35 pm" src="https://user-images.githubusercontent.com/1148709/48880150-50d44500-edcc-11e8-98c2-016af36fac73.png">
<img width="1243" alt="screen shot 2018-11-21 at 8 25 47 pm" src="https://user-images.githubusercontent.com/1148709/48880151-50d44500-edcc-11e8-970f-1d6fb249cda9.png">
<img width="276" alt="screen shot 2018-11-21 at 8 25 24 pm" src="https://user-images.githubusercontent.com/1148709/48880152-50d44500-edcc-11e8-98ab-6c62afd9f910.png">

**Comment by mooreds** [comment]
I just clicked through the example issues on the site in Edge `Version 92.0.902.78 (Official build) (64-bit)` and it looks fine. Probably good because Edge moved to Blink/Chromium, rather than Trident a while ago.

Closing.
