### ISSUE TITLE
Search should be navigable with keystrokes

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#100]
The search results from the docs pages ( https://fusionauth.io/docs/v1/tech/ ) should be navigable without using the mouse.

**Comment by robotdan** [comment]
I prototyped the search using the autocomplete library and it worked ok, and supports keyboard nav. 
https://github.com/algolia/autocomplete.js/blob/master/examples/basic.html

**Comment by mooreds** [comment]
This is done now.
