### ISSUE TITLE
Move contributed password hashers/encryptors to fusionauth-contrib

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#1078]
https://github.com/FusionAuth/fusionauth-example-password-encryptor/pull/6#issuecomment-958580853 points out that we should have the contributed password encryptors be in https://github.com/fusionauth/fusionauth-contrib not in the example app.

**Comment by matthewhartstonge** [comment]
Welp, I've broken out my Argon2id contributions:

- https://github.com/matthewhartstonge/fusionauth-argon2id-password-encryptor
- https://github.com/matthewhartstonge/fusionauth-argon2id-native-password-encryptor

**Comment by mooreds** [comment]
Thank you. It's on my list of things to do to push this to the fusionauth-contrib repo.

**Comment by mooreds** [comment]
All done. It got moved over today and the docs are updated.
