### ISSUE TITLE
Get a 401 when I do this and click on sign in for Spring Boot 1.5.x

### ISSUE THREAD

**Issue by djangogao** [FusionAuth/fusionauth-site#11]
https://fusionauth.io/blog/2018/10/24/easy-integration-of-fusionauth-and-spring
https://github.com/FusionAuth/fusionauth-spring-security-example

I deploy the example and it works well. According to my company software situation, 
based on the example, I changed the Spring Boot version to 1.5.x and the 401 error happened.

![TIM图片20190704162633](https://user-images.githubusercontent.com/12482872/60651640-3fcad680-9e79-11e9-9cff-11f7029ea372.png)

Please give me some advice！

**Comment by robotdan** [comment]
@tyduptyler13 have you seen this before?

**Comment by tyduptyler13** [comment]
I think spring changed some of the requirements in later versions and I haven't tracked down the issue. I would say wait for me to finish https://github.com/FusionAuth/fusionauth-spring-security-example/issues/2 because it will likely change/improve all of the edge cases/spring compatibility.

**Comment by mooreds** [comment]
Spring has moved on past this version and we know we need to redo this tutorial (we need to review all the tutorials). Going to close this issue out and track here: https://github.com/FusionAuth/fusionauth-site/issues/915
