### ISSUE TITLE
Update "Adding Social Sign in to your Django Application"

### ISSUE THREAD

**Issue by AkiraBrand** [FusionAuth/fusionauth-site#1101]
1. add `pip install virtualenv to the beginning of "Setting up Django" command section

2. change `Source sb-env/bin/activate` to `source sb-env/bin/activate` (lowercase) 

3. When trying to build the secret birthday's app, following the code exactly leads to a: `ModuleNotFoundError: No module named 'secretbirthdaysapp.urls'`

The full stack trace can be found [here](https://pastebin.com/RrFNFg0k)

**Comment by mooreds** [comment]
Superseded by https://github.com/FusionAuth/fusionauth-site/pull/1630
