### ISSUE TITLE
Add example of theme import with kickstart

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#1103]
"Perhaps a theme import would be good for the example kickstart (I couldn't see one in there)."

From https://github.com/FusionAuth/fusionauth-issues/issues/1492#issuecomment-972945555

**Comment by spenceryonce** [comment]
I second this. Getting tons of errors when trying to creating and update a theme using the Kickstart API service. Someone please post an example of how to properly do this.

**Comment by mooreds** [comment]
Thanks for the feedback, @spenceryonce . You also may want to post on the forum and see if anyone can share an example: https://fusionauth.io/community/forum/

**Comment by mooreds** [comment]
This was completed under https://github.com/FusionAuth/fusionauth-site/pull/1817

Hope this helps you out @spenceryonce

**Comment by mooreds** [comment]
Here's the link to the docs: https://fusionauth.io/docs/v1/tech/themes/kickstart-custom-theme
