### ISSUE TITLE
MFA guide enhancements

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#1154]
I had a call with a client, and there was some confusion around how to use Two Factor. 

The issue ended up being that most of our existing doc pointes the user at self service options and does not necessary describe the use cases for using alternate strategies. 

For example, I think the following uses cases exist - (at least, perhaps others):
1. Self service using themed pages. 
2. Self service using the Two Factor API. 
3. Administratively using the User Create or User Update API. 

In this case, the client was looking for the administrative option and it was not clear this was even possible or a supported use case. 

We likely want to mention these use cases somewhere and then point at the correct API or UI guides accordingly.

**Comment by mooreds** [comment]
Note that you can't actually assign MFA to someone with a message based method without calling 'send'. You don't have to send the code to them, but you have to call 'send', write a webhook, and catch it. Then you can enable two factor with `/api/user/two-factor/<userId>`. 

Related: https://github.com/FusionAuth/fusionauth-issues/issues/1187#issuecomment-828123328

**Comment by mooreds** [comment]
I am wrong, you can just patch the user and add MFA:

```
API_KEY=...

curl -XPATCH -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'https://sandbox.fusionauth.io/api/user/00000000-0000-0000-0000-000000000004' -d '{"user": {"twoFactor": {"methods": [ {"method": "email", "email": "dinesh@aol.com"}] }}}'
```
