### ISSUE TITLE
Release Notes TOC issues

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#117]
The release notes toc is a bit different then the other sub menu navs. 

Here is how I think the liquid template should be built 

```
<li {% if page.url == "/docs/v1/tech/release-notes.html" %}class="open"{% endif %}>
  <a href="#" class="sub-menu"><i class="fal fa-fw fa-list-ol"></i> Release Notes <i class="fal fa-chevron-{% if page.url == "/docs/v1/tech/release-notes.html" %}up{% else %}down{% endif %} fa-fw"></i></a>
  {% if page.showreleasetoc == 1 %}
  <div id="releasenotestoc">
    {{ page.document | tocify_asciidoc }}
  </div>
  {% endif %}
</li>
```

This would work if we can control the HTML that is produced by the `tocify_asciidoc`- not sure where or how that is built. 

I wonder if there is a better way to build this, the nav gets crazy tall when we expand this, and it is only going to get worse. 
We could make a select box on the release notes page and on select it scrolls to the correct version.  We could do that entirely in JavaScript if we want. 

![image](https://user-images.githubusercontent.com/1148709/86158267-c84c7900-bac5-11ea-9ea1-3ecb69339391.png)

**Comment by mooreds** [comment]
@robotdan hmmm. I was trying for a quick win because I found myself always doing a 'cmd-F' to find a particular version. I'm not sure this is worth a full fledged javascript component. 

I thought the long blown out nav would be ok because this is a long blown out page :) . 

Since the length of the nav is problematic, I propose rolling this back.

**Comment by robotdan** [comment]
> Since the length of the nav is problematic, I propose rolling this back.



That sounds good to me. I could add a select box to the page via JS to make it a bit easier to navigate.

**Comment by mooreds** [comment]
Here's the PR to revert: https://github.com/FusionAuth/fusionauth-site/pull/104

**Comment by mooreds** [comment]
Ooops, can't revert it via github, will manually back it out.
