### ISSUE TITLE
Localization for Emails

### ISSUE THREAD

**Issue by shuurai** [FusionAuth/fusionauth-site#12]
Creating a localization for email templates does not work when using none latin based languages such as chinese, japanese and korean.

These characters after saving turns into "?" in the database. The database field collation unicode is correct though. 

The step to reproduce:

1. create localization
2. save the localization
3. save the email template
4. open it up again, all unicode characters becomes ?

![Screen Shot 2019-07-11 at 5 32 39 PM](https://user-images.githubusercontent.com/1995042/61040020-67361c00-a402-11e9-807b-19fd0b5741c0.png)
![Screen Shot 2019-07-11 at 5 33 15 PM](https://user-images.githubusercontent.com/1995042/61040021-67361c00-a402-11e9-870b-b5bde5ccc4bc.png)

**Comment by robotdan** [comment]
Hi @shuurai thanks for letting us know. FusionAuth does support multi-byte characters.

Are you using MySQL? If so, can you confirm that you're configured to use `utf8mb4_bin`? 

https://fusionauth.io/docs/v1/tech/installation-guide/database

**Comment by shuurai** [comment]
Yes, the collation is **utf8mb4_bin**.

As noted, it works when I manually update into the database. However the moment the edit save process is actioned, the text goes to ?.

**Comment by robotdan** [comment]
Hmm.., ok. I'll have to try to recreate. 

A few questions:

1. What operating system and version, and what locale is configured for your OS?
2. What browser, version and language setting are you using?


Thanks!

**Comment by shuurai** [comment]
Simplified Chinese: 账号验证
Traditional Chinese: 帳號驗證

The database used is Postgres.

**Comment by shuurai** [comment]
1. Ubuntu 16 64 bit, Locale is Hong Kong. English.
2. Browser Chrome 75.x

**Comment by robotdan** [comment]
Thanks @shuurai we'll attempt to recreate your symptom. We have been unable to recreate on macOS, I can try on Windows and Ubuntu as well.

**Comment by robotdan** [comment]
This may be a similar issue to https://github.com/FusionAuth/fusionauth-issues/issues/231. 

What is the output from the following commands on your system? An example output shown after the `#. 

```
echo $LANG          # en_US.UTF-8
echo $LC_CTYPE      # en_US.UTF-8
```

There may be an issue that only appears when the underlying system is using something other than UTF-8. We'll continue to investigate.

**Comment by mooreds** [comment]
I was unable to recreate on a version 1.30 using postgres. 

Closing this issue since it is stale. Please re-open if this is still an issue.
