### ISSUE TITLE
Webhook events are all documented as tenant-scoped

### ISSUE THREAD

**Issue by jamestelfer** [FusionAuth/fusionauth-site#1215]
The documentation for all webhook events currently includes the `_tenant-scoped-event.adoc` file indicating that it's tenant scoped.

At least two events (I can't say I've checked them all) include this file, but their example does not include a `tenantId` field: `event.log.create` and `kickstart.success`. Also, `audit.log.create` indicates it's tenant scoped, but the `tenantId` is only present in the `newValue` object definition, not the root of the event.

Looking at all events, it appears that they all have three top-level children of `event`: `id`, `createInstant`, and `type`. A tenant-scoped event also has the `tenantId` field at the top level. Is this correct? If so, I'd love to see this in the event overview topic 🙏 

My working assumption is that this is a simple oversight after the restructure, but any clarification would be great!

As an aside: note that https://fusionauth.io/docs/v1/tech/events-webhooks/events currently 404s.

**Comment by mooreds** [comment]
I think the 404 is an issue with the website redesign; I'll let the folks who can fix it know.

Thanks for catching the tenant un-scopedness. I have a PR out for review that clarifies those particular events. I also scanned the other events and they should all be correctly marked "tenant scoped".

**Comment by jamestelfer** [comment]
Magic! Thanks a lot, that answers my question.
