### ISSUE TITLE
Bottom of pricing page looks a bit wonky on mobile

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#124]
In two places, things are cut off. See attached screenshots.

This is using Firefox on desktop, with the mobile view devtool setting.

Also tested on chrome and firefox on a real android phone and saw similar issues.

<img width="453" alt="Screen Shot 2020-07-07 at 10 21 37 AM" src="https://user-images.githubusercontent.com/91825/86812014-c2154a00-c03b-11ea-9291-cafa9e68b4bc.png">

<img width="494" alt="Screen Shot 2020-07-07 at 10 21 23 AM" src="https://user-images.githubusercontent.com/91825/86812021-c477a400-c03b-11ea-81ee-a0d4340fa2ec.png">

**Comment by voidmain** [comment]
The first one looks fine (intentionally coded that way) if you are referring to the background image. The second is just that the button is so damn BIG! :)

I changed the button text to "DOWNLOAD FOR FREE". That will fit on any device.

If that fix looks good to you, we can close this ticket out.
