### ISSUE TITLE
Retrieve Refresh Tokens API response documentation incomplete

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-site#126]
_[Retrieve Refresh Tokens](https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-refresh-tokens)_ API call documentation misses the description of `refreshTokens[x].startInstant` and `refreshTokens[x].metaData.scopes` response entity attributes.

**Comment by mooreds** [comment]
Should be resolved in https://github.com/FusionAuth/fusionauth-site/pull/946

**Comment by mooreds** [comment]
Oops, forgot scopes.

**Comment by mooreds** [comment]
Closing because #953 fixed.
