### ISSUE TITLE
Complete LinkedIn Login not working with the login API

### ISSUE THREAD

**Issue by Damien-Lavrilleux** [FusionAuth/fusionauth-site#1271]
In the documentation (https://fusionauth.io/docs/v1/tech/apis/identity-providers/linkedin#complete-the-linkedin-login) you only need a data.token to complete the login with linkedin.

But when you do that you get an error from fusionAuth that require data.code and data.redirect_uri.

The documentation is wrong or the fusionAuth API has a validation error there.

![image](https://user-images.githubusercontent.com/20111138/158214164-05fcecbd-f338-41df-94aa-9d540ccc178f.png)

**Comment by mooreds** [comment]
Thanks, the doc is definitely incorrect. Will work on getting it updated.
