### ISSUE TITLE
Update docs to not break words when on desktop

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#130]
Opened from comments to https://github.com/FusionAuth/fusionauth-site/pull/129

```
    <style>
      /* Mobile layout overflow, we could move this into fusionauth-style */
      a, code {
        word-break: break-all;
      }
    </style>
```

This causes weird breakage on the desktop site. See screenshot where the link 'identity provider' splits in the middle of a word: 

<img width="889" alt="Screen Shot 2020-07-10 at 11 34 45 AM" src="https://user-images.githubusercontent.com/91825/87182454-63510a00-c2a1-11ea-91f4-63daf2f688f2.png">

Should move this style to fusionauth-style and have it only apply on mobile devices.

**Comment by robotdan** [comment]
I actually don't mind it wrapping, but I'm happy to add style to fix this on desktop. Any objection to leaving it the way it is? I could go either way.

**Comment by mooreds** [comment]
Let's leave it be!
