### ISSUE TITLE
5-minute setup guide has confusing Applications flow

### ISSUE THREAD

**Issue by troutgirlfusionauth** [FusionAuth/fusionauth-site#1304]
Instructions in the 5-minute setup guide say that new admins can get to the Applications screen EITHER by clicking the Applications tab in the left nav bar OR by clicking the "Setup" button in the "#1 Missing Application" box. However the two actions do not go to the same next screen and it was very confusing to me as I tried to exactly follow the flow.

The Applications tab goes to the screen shown in the setup guide, but clicking the Setup button shows this:

<img width="1514" alt="Screen Shot 2022-04-12 at 3 51 24 PM" src="https://user-images.githubusercontent.com/102994920/163071844-dbdc419e-35e2-4939-a5db-e10d4df366a5.png">

We could either amend the documentation or fix the routing to be identical.

**Comment by mooreds** [comment]
Closing as these were overhauled with the quickstarts
