### ISSUE TITLE
Add System Requirements to ->  https://fusionauth.io/docs/v1/tech/advanced-threat-detection/

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#1367]
Threat Detection is available for Enterprise Customers, but certain system requirements are needed to enable successfully.  We should likely document this.

**Comment by mooreds** [comment]
Is this still an issue, @jobannon ?

**Comment by jobannon** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/1399
