### ISSUE TITLE
Lambdas have same icon as APIs

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#1369]
https://fusionauth.io/docs/v1/tech/ 

The lambda section has the same icon.

It should be different.

**Comment by mooreds** [comment]
Closing as fixed under https://github.com/FusionAuth/fusionauth-site/pull/1457

**Comment by robotdan** [comment]
Did we just remove the lambda icon, or change it? Ideally it would match the icon we use in the FusionAuth admin UI - which I think was the code icon we were using.

**Comment by mooreds** [comment]
We removed it. In the big reshuffle, most second tier menu items lost their icons. The first tier menu items kept them, and the second tier identity providers kept them as well.
