### ISSUE TITLE
Typing Error in Entity Request Body

### ISSUE THREAD

**Issue by LokiLokus** [FusionAuth/fusionauth-site#1383]
Currently in the https://fusionauth.io/docs/v1/tech/apis/entity-management/entities#create-an-entity Page the Request Model to create a Entity is documented as:

```
{
  "entity": {
    "clientId": "092dbded-30af-4149-9c61-b578f2c72f59",
    "clientSecret": "+fcXet9Iu2kQi61yWD9Tu4ReZ113P6yEAkr32v6WKOQ=",
    "data": {
      "companyType": "Legal"
    },
    "entityType": {
      "id": "092dbded-30af-4149-9c61-b578f2c72f57",
    },
    "name": "Raviga"
  }
}
```

But this is wrong, it should be:
```
{
  "entity": {
    "clientId": "092dbded-30af-4149-9c61-b578f2c72f59",
    "clientSecret": "+fcXet9Iu2kQi61yWD9Tu4ReZ113P6yEAkr32v6WKOQ=",
    "data": {
      "companyType": "Legal"
    },
    "type": {
      "id": "092dbded-30af-4149-9c61-b578f2c72f57",
    },
    "name": "Raviga"
  }
}
```

Took me half an hour to find. Please update the Request Models, the Response Models are correct. Same Mistake in Create & Update.

**Comment by mooreds** [comment]
@LokiLokus Heya, thanks for filing this issue! Sorry about that. I just pushed a fix here https://github.com/FusionAuth/fusionauth-site/pull/1384 which should be live in a few minutes.

Thanks again for letting us know!
