### ISSUE TITLE
Audit the IdP Link User API, the request parameters are out of date

### ISSUE THREAD

**Issue by robfusion** [FusionAuth/fusionauth-site#1404]
https://fusionauth.io/docs/v1/tech/apis/identity-providers/links#link-a-user

At minimum. it appears that we accept a displayName in IdentityProviderLinkRequest now, but it is not documented.

See `IdentityProviderLinkRequest`

```
public class IdentityProviderLinkRequest extends BaseEventRequest implements Buildable<IdentityProviderLinkRequest> {
  public String displayName;

  public UUID identityProviderId;

  public String identityProviderUserId;

  public String pendingIdPLinkId;

  public UUID userId;
}
```

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1728

**Comment by robotdan** [comment]
PR
- https://github.com/FusionAuth/fusionauth-site/pull/1425

**Comment by robotdan** [comment]
@jobannon FTW
