### ISSUE TITLE
Apple IdP config key type clarification

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#1446]
Add clarification to the Apple IdP configuration that the key type is EC. 

### Doc
- https://fusionauth.io/docs/v1/tech/identity-providers/apple#import-the-private-key

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/1744#issuecomment-1148621880

**Comment by jobannon** [comment]
PR https://github.com/FusionAuth/fusionauth-site/pull/1447
