### ISSUE TITLE
Make docker install clearer that if using prod mode how to manage schema updates

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#148]
### Description
Make docker install clearer that if using prod mode how to manage schema updates. Currently it just says you'll need to manage it. 

We could point them at the advanced install guide where it describes how to manage the schema and were to download the schema.

**Comment by mooreds** [comment]
This actually looks like it has been done here: https://fusionauth.io/docs/v1/tech/installation-guide/docker/#migrations

@robotdan did you have a different approach in mind?

**Comment by mooreds** [comment]
Closing this out, as it looks like the changes were done previously.
