### ISSUE TITLE
The user core concepts page needs form fields laid out

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#1493]
https://fusionauth.io/docs/v1/tech/core-concepts/users doesn't have form fields explaining every setting, like the other high level core concepts page does. ( https://fusionauth.io/docs/v1/tech/core-concepts/applications for example). 

Should build that out.

**Comment by Aaron-Ritter** [comment]
closed by https://github.com/FusionAuth/fusionauth-site/pull/2413
