### ISSUE TITLE
Stimulate secure coding examples in password-encryptors

### ISSUE THREAD

**Issue by RuudSchellekens** [FusionAuth/fusionauth-site#15]
Although the humor of a "super secure" reverse password hashing class is great, reality oftentimes is that people blindly copy code. I would suggest to include a serious password hashing/encryption example instead and not make "super secure" but actually very insecure examples. Thanks!

Page to update is 
https://fusionauth.io/docs/v1/tech/plugins/password-encryptors

**Comment by robotdan** [comment]
Thanks for the suggestion @RuudSchellekens we do add a warning that says do not use this in production, however your point is well taken. 

We'll review this example, thanks!

**Comment by mooreds** [comment]
Closing because I updated the example.
