### ISSUE TITLE
A simple semantic error in Grant APIs documentation

### ISSUE THREAD

**Issue by munkith-abid** [FusionAuth/fusionauth-site#1510]
In the [Retrieve Grants](https://fusionauth.io/docs/v1/tech/apis/entity-management/grants#retrieve-grants) of the `Grant APIs` documentation, the first line goes like this:
```This API is used to retrieve Grants. Specifying only an entityId on the URI will retrieve all Grants for a single Grant.```
I think the last word is meant to be `Entity` instead, which alters the line to 
```This API is used to retrieve Grants. Specifying only an entityId on the URI will retrieve all Grants for a single Entity.```

**Comment by mooreds** [comment]
Closed under #1511, thanks for reporting.
