### ISSUE TITLE
Inconsistent event types in User Identity Provider Unlink event documentation

### ISSUE THREAD

**Issue by StefanCB70** [FusionAuth/fusionauth-site#1533]
In the documentation page for the [User Identity Provider Unlink](https://fusionauth.io/docs/v1/tech/events-webhooks/events/user-identity-provider-unlink) event, the "Event Type" field towards the top of the page suggests that the event type is `user.delete`. The sample event body further down the page however suggests a more believable type of `user.identity-provider.unlink`. I guess there is a question as to which is correct and which needs changing.

**Comment by mooreds** [comment]
Thanks so much for opening the issue @StefanCB70 . Fixed under https://github.com/FusionAuth/fusionauth-site/pull/1534 and should be deployed in a few minutes.
