### ISSUE TITLE
Update Azure OpenID Connect Integration details for v2

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#156]
Doc page: 
https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/azure-ad

I believe we have a customer that has gotten Azure AD 2.0 configured using OpenID Connect. We can attempt to recreate the configuration and then ensure our documentation is up to date. 

See https://github.com/FusionAuth/fusionauth-issues/issues/153#issuecomment-665971306

**Comment by mooreds** [comment]
Fixed in https://github.com/FusionAuth/fusionauth-site/pull/325
