### ISSUE TITLE
Twilio page refers to page that doesn't exist

### ISSUE THREAD

**Issue by tedyoung** [FusionAuth/fusionauth-site#1572]
On the page https://fusionauth.io/docs/v1/tech/integrations/twilio, the warning at the top says:

> The functionality described therein is deprecated as of 1.26.0. For version 1.26.0 and greater, please reference [here](https://fusionauth.io/docs/v1/tech/messengers).

The target page is 404. I assume it's referring to https://fusionauth.io/docs/v1/tech/apis/messengers/.

**Comment by mooreds** [comment]
Fixed.
