### ISSUE TITLE
Refresh a JWT: POST /api/jwt/refresh - 404 Response

### ISSUE THREAD

**Issue by nikos** [FusionAuth/fusionauth-site#16]
According to the documentation https://fusionauth.io/docs/v1/tech/apis/jwt#refresh-a-jwt it should be possible to refresh a (valid) refresh token with the help of:

```
curl --request POST \
  --url http://localhost:9011/api/jwt/refresh \
  --header 'authorization: -mz.....oc_x0pBniIn-eaXJsF-w....U' \
  --header 'content-type: application/json' \
  --data '{
	"refresehToken": "Zg.....OC-Jf9......................vIQ"
}'
```

... but a HTTP Status 404 (not found) is returned.

NOTE: I tried with and without Authorization Header (ApplicationID should not be required if I interpret the documentation properly).

**Comment by robotdan** [comment]
When using the JWT in the Authorization header you need to specify the schema. 

https://fusionauth.io/docs/v1/tech/apis/authentication#no-authentication-required

For example: `Authorization: JWT <encoded JWT>`

Try this:

```
curl --request POST \
  --url http://localhost:9011/api/jwt/refresh \
  --header 'authorization: JWT -mz.....oc_x0pBniIn-eaXJsF-w....U' \
  --header 'content-type: application/json' \
  --data '{
	"refresehToken": "Zg.....OC-Jf9......................vIQ"
}'
```

**Comment by robotdan** [comment]
Also, no big deal, but this issue would be better opened here https://github.com/FusionAuth/fusionauth-issues/issues

**Comment by nikos** [comment]
Thanks Daniel, unfortunately fixing the authorization header didn't solve the 404 issue, when POSTing to `/api/jwt/refresh`, could it be that using HTTP GET would be the solution?

**Comment by robotdan** [comment]
Not sure if your example was a typo, or if that is what you're sending in, but I noticed your JSON request body is incorrect, you had `refresehToken ` instead `refreshToken` , that would cause a `404`. 

Also, you do not need the `Authorization` for this API, I should have caught that earlier, I didn't notice. That doesn't seem to be causing you any issues, if it was you'd be getting a `401`. 

```
curl --request POST \
  --url http://localhost:9011/api/jwt/refresh \
  --header 'authorization: JWT -mz.....oc_x0pBniIn-eaXJsF-w....U' \
  --header 'content-type: application/json' \
  --data '{
	"refreshToken": "Zg.....OC-Jf9......................vIQ"
}'
```

**Comment by nikos** [comment]
Thanks for figuring out the typo, indeed the proper key "refreshToken" in the JSON payload fixes the 404 and I can now retrieve successfully a new token. Just wondering if returing an HTTP status 400 (=> malformed request syntax) instead of 404 would be more obvious for a client?

**Comment by nikos** [comment]
> Also, no big deal, but this issue would be better opened here https://github.com/FusionAuth/fusionauth-issues/issues unless you think there is a documentation bug. If that is the case - this is just fine! :-)

With the thread discussion up to now: probably in both trackers ;-) ... it would be great to see in the documentation also some typically error cases covered, so that the developers can be self guided towards a solution.

**Comment by robotdan** [comment]
Great, glad to hear it is working for you. Thanks for the feedback @nikos, appreciated. 

I think you're correct, in this case, we should have returned a `400` and indicated the request body was missing the `refreshToken` property. 

I'll use this issue to fix that, it will in the upcoming release. 

Thanks for the feedback, keep it coming!

**Comment by SigitArif** [comment]
Hi @robotdan 
may I ask why we only get the "token" response in this /api/jwt/refresh API while in the documentation it is said that it will return "token" and "refreshToken"

**Comment by robotdan** [comment]
The response will contain a `refreshToken` if you provide one on the request, and if you have refresh tokens enabled for the Application. 

In the UI, see `Applications > Edit > Security > Generate Refresh Tokens` and `Enable JWT Refresh`. 

And if those are enabled, make sure you are passing a refresh token on the request in the form of a cookie or in the request body. If you are using Postman, Insomnia, or other REST client, make sure if it is storing cookies for you they are not stale values.

**Comment by SigitArif** [comment]
![image](https://user-images.githubusercontent.com/47412237/94632964-27ed3700-02f6-11eb-8053-b23e19d3bd45.png)
just like this one? Where is the Enable JWT Refresh button?
Yes I already provide the previous refreshToken in request body but not in cookies

**Comment by robotdan** [comment]
You must have just an older version, the `Allow token refresh` is equal to `Enable JWT refresh`, we must have changed the label.

**Comment by SigitArif** [comment]
Oh I see. Then what can I do now to get the refreshToken response? Do I need to upgrade to the latest fusionauth version?

**Comment by SigitArif** [comment]
![image](https://user-images.githubusercontent.com/47412237/94635462-e4e29200-02fc-11eb-8000-168a18ba707e.png)
I already provide the refreshToken in the request body

**Comment by robotdan** [comment]
No need to upgrade, your configuration looks ok. 

You are using Postman, if you are not receiving a refresh token in the response, it is likely because Postman is sending a cookie named `refresh_token` which takes precedence over the one in the request body. 

Click the "Cookies" text in the top right , and clear your cookies, specifically the `access_token` and `refresh_token` cookies.

**Comment by SigitArif** [comment]
![image](https://user-images.githubusercontent.com/47412237/94636738-fda07700-02ff-11eb-8182-275d4c8840e4.png)
I already clear it before but it always keep generating the new one when I hit the API. Any idea?

**Comment by robotdan** [comment]
This is working as designed, postman will behave as a user-agent and store the cookies returned to it. You can either turn this feature off in Postman or delete cookies manually if you won't want to use them. 

This is not an issue with FusionAuth.

**Comment by SigitArif** [comment]
But actually it also happen in my application layer (node js) when it consume this api/jwt/refresh API. I just send the request body, without any cookies

**Comment by robotdan** [comment]
If you think you have encountered an error with FusionAuth, please open a new issue and we can track it there. Thanks!

**Comment by SigitArif** [comment]
Okay
