### ISSUE TITLE
Redirect URL config in Okta example for SAML v2 IdP Initiated login

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#1619]
Page: https://fusionauth.io/docs/v1/tech/identity-providers/samlv2-idp-initiated/okta#undefined

Items to review:
- Okta config to ensure IdP linking occurs correctly. In the default configuration Okta does not seem to send a unique Id. Ideally we'd document how to configure Okta to use a NameID Format of persistent, and still send the email attribute. 
- Document how to provide a `redirect_uri` to FusionAuth via the Okta config. This can be done by adding `?redirect_uri={redirect_uri}` to the configured ACS, or some IdPs use `RelayState` for this purpose. We don't currently support that, but we could look at adding it. 
    - https://github.com/FusionAuth/fusionauth-issues/issues/1785
- Review the `Configure the FusionAuth Application Redirect URL` section, we may be making some assumptions here with redirect and grant configuration.

**Comment by jobannon** [comment]
> Okta config to ensure IdP linking occurs correctly. In the default configuration Okta does not seem to send a unique Id. Ideally we'd document how to configure Okta to use a NameID Format of persistent, and still send the email attribute.

Figured this part out.  Can make this part of the tutorial or make it "an extension"
