### ISSUE TITLE
Add documentation about using FusionAuth in a CI environment

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#1663]
FusionAuth can be used in a continuous integration/testing environment quite easily. We should document how to do so:

* setting it up in GitHub actions
* using kickstart to set the system up to a known state (example here: https://github.com/FusionAuth/fusionauth-python-client/blob/master/.github/workflows/test.yaml)
* use selenium or some other end to end test functionality (can a user log in)

**Comment by mooreds** [comment]
Removing sonderformat folks as they are focusing on other work.

**Comment by mark-robustelli** [comment]
Added - [PR 2820](https://github.com/FusionAuth/fusionauth-site/pull/2820)
