### ISSUE TITLE
Doc on migrating users misleading

### ISSUE THREAD

**Issue by robw-fusionauth** [FusionAuth/fusionauth-site#1675]
There is a misleading statement in the FusionAuth doc on migrating users with a FusionAuth connector ([https://fusionauth.io/docs/v1/tech/connectors/#authentication]).

In the section on "Suggested Fields" it states that if you are migrating a user, you can populate the `user.insertInstant`: field in the newly created migrated user record, typically assigning it the value of the `insertInstant`  attribute from user's record in the migrated-from system. 

It's not possible to assign anything to the `insertInstant` field. That's because when FusionAuth creates a new user record (from the admin UI, a user self-serve registration, or a connector migration as in this case), the `insertInstant` and `lastUpdateInstant` fields are automatically populated with the current date by the code that creates the new user record. 

It's clear that are use cases where the migrated user's original `insertInstant` date is important, (e.g.: for subsequent searching and reporting), in which case the exported value could be readily loaded a suitably named new user's `user.data...` attribute.

The doc should be revised to make this situation clear, lest developers writing migration connector code are misled.

Rgds
Rob Wombwell

**Comment by mooreds** [comment]
Hmmm. I just did a test and determined you can set the insertInstant when you are using the User Import API. However, I looked at the code and agree that the insertInstant field will not be taken from the user object during a connector login. Will update.

**Comment by mooreds** [comment]
Closing, thanks for filing!

**Comment by robw-fusionauth** [comment]
Thanks Dan, that's great
