### ISSUE TITLE
Validate email template when taking a user action in the UI to ensure it renders

### ISSUE THREAD

**Issue by seletonurb** [FusionAuth/fusionauth-site#17]
### Problem

In the admin UI you can action a user with an email template that is not designed to send directly - and instead is only meant to be sent through the Change Password workflow. 

When you configure an action with the Change Password template, it fails silently because it cannot be rendered without a `changePasswordId`.

### Solution

FusionAuth could render this template as part of validation, or synchronously render it to ensure it will be able to be sent so we can provide a meaningful error in the UI. Perhaps as simple as, `The requested email template failed to render properly, see the Event Log`.

### Original title
Replacement variables configured in email templates throw an Exception

### Original Issue
Hello, 

I am having an issue with the replacement variables changePasswordId and verificatoinId for email templates.

I tried to follow the instructions described here: https://fusionauth.io/docs/v1/tech/email-templates/email-templates 

My fusionauth DB is compatible with version 1.7.1 and my server is running on FusionAuth™ version 1.7.2

When I try to send an e-mail through an User Action that is configured to use an e-mail template, I have the following error:

```
fusionauth_1  | Aug 27, 2019 2:06:34.637 PM ERROR io.fusionauth.api.util.EmailTools - An [Error] EventLog with Id [16] was created.
fusionauth_1  | {
fusionauth_1  |   "id" : 16,
fusionauth_1  |   "insertInstant" : 1566914794630,
fusionauth_1  |   "message" : "Email send failure. See reasons below.\n\nRender Errors\n---------------\nhtml : freemarker.core.InvalidReferenceEx
ception: The following has evaluated to null or missing:\n==> changePasswordId  [in nameless template at line 14, column 58]\n\n----\nTip: If the
failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDe
fault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole ex
pression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??\n----\n\n----\nFTL stack trace (\"~\" means nesting-related):\n\t-
 Failed at: ${changePasswordId}  [in nameless template at line 14, column 56]\n----\n\n",
fusionauth_1  |   "type" : "Error"
fusionauth_1  | }
fusionauth_1  | Aug 27, 2019 2:22:59.170 PM ERROR io.fusionauth.api.util.EmailTools - An [Error] EventLog with Id [17] was created.
fusionauth_1  | {
fusionauth_1  |   "id" : 17,
fusionauth_1  |   "insertInstant" : 1566915779164,
fusionauth_1  |   "message" : "Email send failure. See reasons below.\n\nRender Errors\n---------------\nhtml : freemarker.core.InvalidReferenceEx
ception: The following has evaluated to null or missing:\n==> verificationId  [in nameless template at line 14, column 58]\n\n----\nTip: If the fa
iling expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefa
ult, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expr
ession, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??\n----\n\n----\nFTL stack trace (\"~\" means nesting-related):\n\t- F
ailed at: ${verificationId}  [in nameless template at line 14, column 56]\n----\n\n",
fusionauth_1  |   "type" : "Error"
fusionauth_1  | }
```

This is my e-mail template:
```
<style>
  body {
    font-family: "arial", Sans-Serif;
  }
</style>


<p>
Dear user,
</p>


Click on the following link to reset your password.
<p><a href="https://mydomain.com/password/change/${changePasswordId}">https://mydomain.com/password/change/${changePasswordId}</a></p>


After you have reset the password, please sign in to :
  <p><a href="https://myapp.com">https://myapp.com</a></p>

<p>
If you have any questions, please reply to this mail.
</p>
<p>
Kind regards,
</p>
<p>
Support Team

</p>
```

When I sent an e-mail though an User Action with templates without the replacement variable changePassowrdId, it works. I successfully receive the message.

Maybe I forgot to configure something?

Best regards,
Bruno.

**Comment by seletonurb** [comment]
Hi @robotdan, thank you for the clear reply. 

Yes, I configured an User Action with a Change Password e-mail template, and then, through the Fusionauth UI, I hit on the Action User button to apply that action. This does not work indeed. The problem that I see is that it silently fails, making the user think the e-mail will be sent. I think that a simple UI notification telling that the workflow is not supported might be helpful for the user.

However, I could trigger this workflow using the API, so it works.

I am closing this issue but if you think this should be open until the workflow is supported in the UI, please let me know and I can reopen.

Best regards,
Bruno.

**Comment by robotdan** [comment]
Thanks for the feedback @seletonurb. 

> The problem that I see is that it silently fails, making the user think the e-mail will be sent. I think that a simple UI notification telling that the workflow is not supported might be helpful for the user.

We've discussed this in the past, it is a good idea. One of the problems is that the email templates do not have types, so we don't actually know that this template is not supported to be sent in this fashion. We could check the name, but that is modifiable.

One option would be to perform a validation check on the email template to ensure we can render it successfully so that we could error earlier. When we do fail to render a template and send it, there will be an error in the Event Log (Settings --> Event Log). However as you point out, because there is not an error shown to the admin, they would not have reason to check the Event Log. 

We could use this issue as a bug / enhancement to do a better job of pre-validation so we can provide an interactive error to the user attempting to take this action in the UI.

> I am closing this issue but if you think this should be open until the workflow is supported in the UI, please let me know and I can reopen.

Can you open a new issue / feature for an admin user to start the "Change Password" workflow from the manage user UI?

**Comment by mooreds** [comment]
Closing this because this is not a site issue. If you'd like this issue to be addressed, please open an issue in this repo: https://github.com/fusionauth/fusionauth-issues/issues
