### ISSUE TITLE
API Documentation for Tenants incomplete

### ISSUE THREAD

**Issue by markschmid** [FusionAuth/fusionauth-site#18]
It seems that the documentation for /api/tenants is not reflecting some of recent changes.
Missing elements are (there might be more):
```
tenant.externalIdentifierConfiguration.changePasswordIdGenerator
tenant.externalIdentifierConfiguration.emailVerificationIdGenerator
tenant.externalIdentifierConfiguration.passwordlessLoginGenerator
tenant.externalIdentifierConfiguration.registrationVerificationIdGenerator
tenant.externalIdentifierConfiguration.setupPasswordIdGenerator
tenant.issuer
tenant.jwtConfiguration
```

I understand those elements have been moved from "System configuration" to the tenant level. 
In the meantime, the API error messages are helpful enough to be able to work with tenants via the API.

Edit: This is for version 1.9.2

**Comment by tyduptyler13** [comment]
Hi,

We wanted to let you know that we are aware. We have all been cranking away on a new website and some of our usual chores have been delayed to get this out as soon as possible. We will get the docs updated after the new site is released. Thanks for your patience.

-Tyler
