### ISSUE TITLE
Consider adding a FusionAuth to FusionAuth migration guide

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#1815]
This would cover items to consider migrating, etc.

The specific request was: "Migrating part of the tenant/user information from one FA instance to another would be handy."

Added to this part of doc:
https://fusionauth.io/docs/v1/tech/migration-guide/

Internal https://fusionauth.slack.com/archives/C0400PUGTRA/p1671724440265489?thread_ts=1671723463.698489&cid=C0400PUGTRA

So, similar to the https://fusionauth.io/docs/v1/tech/admin-guide/configuration-management but with a specific eye towards "I set up system A just how I want it (but didn't necessarily use a tool, how do I get system B in the same state?".

**Comment by sixhobbits** [comment]
potentially partially resolved by https://github.com/FusionAuth/fusionauth-site/pull/3230

**Comment by mooreds** [comment]
Looks resolved to me.
