### ISSUE TITLE
Reaffirm in docs about deactivating a license that the instance will not lose its configuration

### ISSUE THREAD

**Issue by MPH-DZP** [FusionAuth/fusionauth-site#1819]
https://fusionauth.io/docs/v1/tech/admin-guide/licensing#deactivating-your-license explains that one can deactivate a license to rotate the ID. This is an action that seems potentially at risk of removing all theming and other configuration, so it would boost confidence if the doc also confirmed that such config will not be lost.

**Comment by mooreds** [comment]
Closing since I added documentation in #1821 .
