### ISSUE TITLE
MFA guide links to issue that is now closed

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-site#1830]
The guide at https://fusionauth.io/docs/v1/tech/guides/multi-factor-authentication has a link [manage this check is an open feature request](https://github.com/FusionAuth/fusionauth-issues/issues/763)

This issue is closed.  The link should be removed and surrounding text updated.

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/1991
