### ISSUE TITLE
OAuth Modes page should show OAuth 2.0 flow being used for each scenario

### ISSUE THREAD

**Issue by leonroy** [FusionAuth/fusionauth-site#1832]
Nice doc here [OAuth Modes](https://fusionauth.io/docs/v1/tech/core-concepts/modes#third-party-service-authorization).

It'd be great if for each one it mapped to which OAuth 2.0 flow is being used behind the scenes: https://oauth.net/2/grant-types/ otherwise it's just describing a few scenarios rather than tying them to actual reference OAuth flows.

**Comment by mooreds** [comment]
Thanks @leonroy .

Modes are orthogonal to the grant types, but rather depend on the ownership of the various pieces of the system (the client, the resource server, the authorization server). So you can use the authorization code grant, client credentials grant, or other grant with any of the modes.

I can take a todo to update the doc to make that more clear.

**Comment by mooreds** [comment]
Fixed under https://github.com/FusionAuth/fusionauth-site/pull/1840
