### ISSUE TITLE
missing ExternalJWT login API doc

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#184]
This API section should document the login API, similar to the rest of the types that have a `Complete the Facebook Login
Request` section. 
https://fusionauth.io/docs/v1/tech/apis/identity-providers/external-jwt

This should more/less be the same as the JWT Reconcile doc. 
https://fusionauth.io/docs/v1/tech/apis/jwt#reconcile-a-jwt

WE could review this and decide if we want to fully deprecate the JWT Reconcile API since it just calls through to the IdP Login API. This API was a legacy API prior to IdPs.

**Comment by robotdan** [comment]
@jobannon not sure if this is still an issue, but can you check it out, and either close this one out, or handle? Thanks!

**Comment by mooreds** [comment]
Assigning this to me.

**Comment by mooreds** [comment]
This was addressed in https://github.com/FusionAuth/fusionauth-site/pull/1008 and should be resolved when that is merged.

**Comment by mooreds** [comment]
Closing, #1008 fixes.
