### ISSUE TITLE
Broken link to Account Management

### ISSUE THREAD

**Issue by robertregnier** [FusionAuth/fusionauth-site#1893]
The link to Account Management on [this page](https://fusionauth.io/docs/v1/tech/core-concepts/integration-points#oauthoidcsaml) navigates to https://fusionauth.io/docs/v1/tech/account-management which gives a not found 401 error.

**Comment by mooreds** [comment]
Thanks, this is fixed under #1894. Appreciate the report. Should be live in 5 min.
