### ISSUE TITLE
Client secret is not required

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#19]
On the openid connect config the doc shows the client secret parm as required. It is optional.

**Comment by mooreds** [comment]
Is this fixed? I'm guessing this is the appropriate doc and it shows the `client_secret` as optional.

https://fusionauth.io/docs/v1/tech/apis/identity-providers/openid-connect

**Comment by robotdan** [comment]
I think this is to update a screen shot
https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/#create-an-openid-connect-identity-provider

**Comment by mooreds** [comment]
Hmmm. I just looked at 1.30.1 and the client secret is still required. From the API docs:

```
    The top-level client secret to use with the OpenID Connect identity provider.

    Required when identityProvider.oauth2.clientAuthenticationMethod is client_secret_basic or client_secret_post.
```

So it looks like the screenshot should still show client secret as required.

However, I think updating the screenshot is still useful since we don't show the linking strategy field. Will proceed.

**Comment by mooreds** [comment]
When https://github.com/FusionAuth/fusionauth-site/pull/918 is merged, this issue should be resolved.

**Comment by mooreds** [comment]
Closing because the doc was updated.
