### ISSUE TITLE
Document Wildcard usage in Redirect URLs

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-site#2004]
As of FusionAuth 1.43.0, `Authorized redirect URLs` and `Authorized Origins` are permitted to use a wildcard (*) in place of various components of a URL, however, their usage, including limitations, is not documented. Additionally, the field `URL Validation` on the OAuth2 tab needs to be documented.  

Related feature:
 - https://github.com/FusionAuth/fusionauth-issues/issues/437

Places to update
 - [x] https://fusionauth.io/docs/v1/tech/apis/applications
 - [x] https://fusionauth.io/docs/v1/tech/core-concepts/applications
 - [x] ❌ https://fusionauth.io/learn/expert-advice/oauth/modern-guide-to-oauth#redirect-and-retrieve-the-tokens
 - [x] https://fusionauth.io/docs/v1/tech/oauth/#configure-application-oauth-settings
 - [x] ❌ https://fusionauth.io/docs/v1/tech/oauth/endpoints#token - might need a note here

**Comment by spwitt** [comment]
Not going to update "Modern Guide to OAuth" because it is general information and advice on OAuth, not directly related to FusionAuth.

**Comment by spwitt** [comment]
Not sure what to update on https://fusionauth.io/docs/v1/tech/oauth/endpoints, so I'm leaving that one unchanged.

All mentions of redirect reference other pages.

**Comment by robotdan** [comment]
Internal:
- https://github.com/FusionAuth/fusionauth-site/pull/2026
