### ISSUE TITLE
Two Factor/Multi-Factor API Disable Multi-Factor should take an `applicationId` as a query parameter

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-site#2028]
All API endpoints that use query parameters and take an `applicationId`, should be able to send them in the `Request Body` and as query parameters. 

Document the usage of `applicationId` as a query parameter for  Disable a single multi-factor method by User Id, once the functionality is built. 

 - https://fusionauth.io/docs/v1/tech/apis/two-factor#disable-multi-factor

**Comment by robotdan** [comment]
I think this is already complete.
