### ISSUE TITLE
Create a Link API since 1.43.0 should take a token on the request body

### ISSUE THREAD

**Issue by jaywood128** [FusionAuth/fusionauth-site#2035]
Create a Link API since 1.43.0 should take a token on the request body

https://fusionauth.io/docs/v1/tech/apis/identity-providers/links#link-a-user

- https://github.com/FusionAuth/fusionauth-issues/issues/1747

**Comment by robotdan** [comment]
Moving here: 
- https://github.com/FusionAuth/fusionauth-issues/issues/2622
