### ISSUE TITLE
Probable typo of "date" as "data"

### ISSUE THREAD

**Issue by amark-axcient** [FusionAuth/fusionauth-site#2069]
https://fusionauth.io/docs/v1/tech/admin-guide/monitor

in the Monitoring Summary Table

in the "Contains" column of the Login records

```
Each successful login is recorded here. Includes IP information, application, user, and data stamp.
```
is likely meant to read
```
Each successful login is recorded here. Includes IP information, application, user, and _date_ stamp.
```

**Comment by spwitt** [comment]
Thanks for pointing this out @amark-axcient. I've merged a pull request that corrects this from `data stamp` to `timestamp` as the value is actually a timestamp rather than only the date.
- https://github.com/FusionAuth/fusionauth-site/pull/2070
