### ISSUE TITLE
Switchboard customer story has 10log text description

### ISSUE THREAD

**Issue by heitortsergent** [FusionAuth/fusionauth-site#2076]
On the [customers and partners](https://fusionauth.io/customers-partners) page, the Switchboard and 10log customer stories have the same description:

<img width="824" alt="Screenshot 2023-04-06 at 11 13 24 AM" src="https://user-images.githubusercontent.com/446316/230443733-7bf0a03b-032c-46fb-96d3-a0d4ff3ca9c3.png">

**Comment by SeanBobby** [comment]
Updated
