### ISSUE TITLE
YouTube videos mobile formatting issues

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#208]
Our YouTube videos don't size real well for mobile. This may be only in docs, note sure. 

For example, the HYPR video added under https://github.com/FusionAuth/fusionauth-site/pull/203 is one example. 

Local URL: https://site-local.fusionauth.io/docs/v1/tech/identity-providers/hypr
Public URL: https://fusionauth.io/docs/v1/tech/identity-providers/hypr

We will likely need to add some style to `fusionauth-style` to handle these better.

**Comment by voidmain** [comment]
Fixed.
