### ISSUE TITLE
Probable typo of "SaaS" as "SasS" in blog

### ISSUE THREAD

**Issue by bewalt** [FusionAuth/fusionauth-site#2082]
[Blog here](https://fusionauth.io/blog/2023/03/20/switchboard-reduced-migration-time)

In this blog:

Dan: What problems did we solve for you?

Theo: As a **_SasS_** company, we want to be able to support any kind of auth that a user might be using along with integrating SSO when working with enterprise customers.

I believe it should be SaaS

**Comment by mooreds** [comment]
Thanks @bewalt . I just fixed it. Should be live in a few min.
