### ISSUE TITLE
Typo in alt-text of SVB blog

### ISSUE THREAD

**Issue by bewalt** [FusionAuth/fusionauth-site#2089]
In the blog [How FA is affected by the SVB failure](https://fusionauth.io/blog/2023/03/10/fusionauth-and-svb), the alt-text reads, "Wondering how FusionAuth is affected by the failure of **SVN**? Read this post to find out."

![Screenshot 2023-04-13 at 2 07 39 PM](https://user-images.githubusercontent.com/100975673/231871499-aed813bc-97d5-44e5-95ad-06e6256d865f.png)

Should be SVB. Thanks!

**Comment by mooreds** [comment]
Should be fixed by https://github.com/FusionAuth/fusionauth-site/commit/9be83ebfbd9e08015abe567a8a8b12fe029ea605
