### ISSUE TITLE
Features menu overflow on mobile

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#213]
See screenshot.

I see this with firefox and safari when resized to mobile screen widths. See how 'reactor' overflows 'pricing'?

![Screen Shot 2020-09-21 at 9 26 51 AM](https://user-images.githubusercontent.com/91825/93786782-f0db9f00-fbec-11ea-9ad2-580cb06d6a48.png)

**Comment by voidmain** [comment]
Fixed
