### ISSUE TITLE
Write guide on device number limiting

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#2148]
Write a guide on how to limit the number of devices that can be logged into a system 

FusionAuth does not directly support this use case, but you should be able to create your own solution using FusionAuth's APIs.

Here are some features of FusionAuth that may be helpful for implementing this functionality:
- Retrieve a user's session information via the [JWT Retrieve Refresh Tokens API](https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-refresh-tokens)
- Use the [JWT Revoke Refresh Tokens API](https://fusionauth.io/docs/v1/tech/apis/jwt#revoke-refresh-tokens) to revoke refresh tokens by user, application, Id, or value
- Use the [user.login.success](https://fusionauth.io/docs/v1/tech/events-webhooks/events/user-login-success) webhook to trigger a session count check on your side and fail the login if they have too many active sessions

There are two ways to do this, please cover both.
* You can use the webhook to prevent creation of new sessions, with a custom error message on the login screen. This is quick and secure, but not an optimal user experience (because the webhook error message isn't rich and there may be more than one webhook failing login, causing confusion over what caused the failure).
* Modify your application so that after the user logs in, you use the refresh tokens above to see how many devices are logged in. There you can present more options: "you are logged in on 3 devices and are only allowed 2. Please select which device to log out of". When a device is selected, then the refresh token would be revoked for that device.

This also implies a relatively short JWT lifetime (5 min?) so please configur that.

FusionAuth only captures limited information about each device as part of the session information. Devices are not tracked separately, and a user may have multiple sessions on the same device (e.g. on different browsers or in a private browsing mode). So a device is really anything where a user logs in (chrome and firefox on the same computer are two 'devices').

Mention a couple of open GitHub issues requesting a similar feature:
- https://github.com/FusionAuth/fusionauth-issues/issues/1363
- https://github.com/FusionAuth/fusionauth-issues/issues/1156

**Comment by sixhobbits** [comment]
@mooreds - do you have any preferred language/framework for the example application here?

**Comment by mooreds** [comment]
@sixhobbits node/express or python flask is preferred. I'd start with one of the quickstarts and augment that. (That's what I did for the anonymous user guide).

If those languages don't work, let me know what you'd like to use.

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2889
