### ISSUE TITLE
Terraform example

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#2213]
Write a docs page on how to use terraform to manage your FusionAuth instance.

* how to get an API key
* how to add an application
* how to update an application
* how to delete an application

**Comment by Aaron-Ritter** [comment]
@mooreds how complete should the example be? 
- we could include building fusionauth with terraform
- also building an application with terraform
- and then using the provider in relation to the actual application example

**Comment by mooreds** [comment]
This is more of a tutorial on how to use Terraform than how to integrate a webapp. The prerequisite would be a running FusionAuth instance.

Here's the outline I imagine:

* prerequisites (FusionAuth, terraform)
* installing the FusionAuth terraform provider
* how to get an API key from FusionAuth you can use
* how to add an application configuration using the provider
* how to update an application configuration (maybe add another authorized redirect URL) using the provider
* how to disable an application (because it is no longer used) using the provider

No need to talk about building infra for an external webapp with terraform or integrating webapp (nodejs, rails, etc) code with FusionAuth.

**Comment by Aaron-Ritter** [comment]
@mooreds while writing down the documentation and re-testing we discovered that the previously tested `terraform import` command works, but the import configuration does not (which is the proper way from a reproducible perspective). I've created https://github.com/gpsinsight/terraform-provider-fusionauth/issues/214. Should we try and analyse and fix it or do you know if this is already being worked on?

The Data Source configuration works, and I am finishing the rest of the documentation in the meantime, so we could release it without import for now.

**Comment by Aaron-Ritter** [comment]
@mooreds this is ready for review, there are in theory 2 TODOs I added as comments for screenshots, but I don't think they are necessary and the doc is already very long
