### ISSUE TITLE
update to client secrets table 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#2259]
Page:
- https://site-local.fusionauth.io/docs/v1/tech/oauth/endpoints#client-secret-table

The table used to describe when the `client_secret` is required isn't quite correct. 

1. Instead of calling out where the `client_secret` is required - body or header, we should just say it is required. The `client_secret` can be provided in the Basic auth header, or in the request body. 
2. You can always send PKCE, so instead of saying `N/A` shouldn't we say `yes` or `no` indicating if it is used by the caller?

**Comment by alex-fusionauth** [comment]
@robotdan I am not sure I follow fully, on point 1.

If clientAuthenticationPolicy is set to false then you don't need the `client_secret` we should still decide if it is required.
<img width="834" alt="image" src="https://github.com/FusionAuth/fusionauth-site/assets/139158618/b2a345e5-db32-4adf-8f1a-83283910e68d">

Are you trying to eliminate a column and combine the entries to include a single `YES` in one column that has `or`?

<img width="848" alt="image" src="https://github.com/FusionAuth/fusionauth-site/assets/139158618/a65cde94-dc89-4124-8d26-9c8490a22cc9">

On point 2, it seems like `N/A` would make it seem like `either` in my book. This one feels legit to me in that case. We don't want to say a hard `NO` to confuse anyone.

**Comment by alex-fusionauth** [comment]
@robotdan thoughts on this one?

**Comment by robotdan** [comment]
For point 1, the client authentication policy does not have anything to do with how the `client_secret` is provided. In other words, it is required or not required. When it is required, it can be provided in the body or the header. 

So they aren't really discrete use cases, and I think it would allow us to simplify the table. The doc for the token endpoint, which is where the `client_secret` is used, already documents how to provide the value in these different ways. 

For point 2, regardless of your policy, if you provide PKCE, it will be used and validated. So I guess I am fine with leaving it as `N/A` - my concern was just that I don't want it to sound like we ignore PKCE in this configuration. 

Let me know if you want to discuss further.
