### ISSUE TITLE
ERROR: Role "fusionauth" is a member of "fusionauth" in silent mode

### ISSUE THREAD

**Issue by kavanpuranik** [FusionAuth/fusionauth-site#2269]
We are running into this error on multiple test environments since upgrading from `1.40.0` to `1.44.0` on startup:

```
ERROR com.inversoft.maintenance.db.DatabaseSilentModeWorkflowTask - ERROR: role "fusionauth" is a member of role "fusionauth"
```

It looks to be running a GRANT sql but incorrectly trying to grant membership recursively. 

Can you please help us figure out why `DatabaseSilentModeWorkflowTask` is trying to run this SQL, and the logic behind it, so that we can try to figure out if it's a configuration issue? 

Environment details:
- fusion-auth 1.44.0 (Docker) running on ECS single node.
- PostgreSQL 14.3 running on RDS

This issue was previously reported in https://fusionauth.io/community/forum/topic/2090/error-role-fusionauth-is-a-member-of-fusionauth . The solution mentioned there suggests running the migration manually. In our case, the migration did succeed as we can see the updated version in `version` table. So the original upgrade to 1.44.0 ran fine, but at some point later when fusionauth was restarted, fusionauth ran into the above error, and got stuck in maintenance mode.

if I disable silent mode, then fusionauth startups fine, but that's not a good long term solution.

Thanks for your help on this.

**Comment by robotdan** [comment]
This looks like a bug report, can you post this in https://github.com/FusionAuth/fusionauth-issues/issues instead?

**Comment by kavanpuranik** [comment]
Posted here: https://github.com/FusionAuth/fusionauth-issues/issues/2350
