### ISSUE TITLE
Remove duplicate "OAuth Grants" section in The Modern Guide To OAuth

### ISSUE THREAD

**Issue by dolevelb** [FusionAuth/fusionauth-site#2287]
Part of the section in the docs is duplicate:
https://fusionauth.io/articles/oauth/modern-guide-to-oauth#oauth-grants
https://fusionauth.io/articles/oauth/modern-guide-to-oauth#oauth-grants-1

![image](https://github.com/FusionAuth/fusionauth-site/assets/128965179/d0d3444e-9acd-4f26-89dc-11671219bce2)

**Comment by mooreds** [comment]
Weird, thanks! We recently moved that article, so maybe there was some copy/paste errors.

Thanks for filing the bug @dolevelb !
