### ISSUE TITLE
Remove language about session pinning on scaling 

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#230]
In 1.19.0, we removed HTTP sessions. 

https://fusionauth.io/features/scalability

> ### Lightweight Sessions
> While some components of FusionAuth use sessions and require session pinning, our sessions are lightweight. This means a single server can handle tens of thousands of sessions or more.

Maybe update to: 

> ### Stateless
> Horizontal scaling is easy because each FusionAuth instance is stateless.  

Needs more meat still...

**Comment by robotdan** [comment]
Any one of us can make this change, but we should sync up on the copy.

**Comment by mooreds** [comment]
How about

> ## Statelessness
> Horizontal scaling is easy because each FusionAuth instance is stateless. Need to support more users? Just add more nodes.

**Comment by robotdan** [comment]
Statelessness seems hard to say, I would just say "Stateless".

**Comment by robotdan** [comment]
Added a comment. Thanks!

**Comment by mooreds** [comment]
This was done a while ago, closing.
