### ISSUE TITLE
Go Lang Quickstart Flow

### ISSUE THREAD

**Issue by alex-fusionauth** [FusionAuth/fusionauth-site#2329]
provicer should be provider

https://github.com/FusionAuth/fusionauth-site/blob/7a48764e621a42a79d93368b041f30dd7b3a788f/astro/src/content/quickstarts/quickstart-golang-web.mdx#L176

Should this be the full code block or just imports?

https://github.com/FusionAuth/fusionauth-site/blob/7a48764e621a42a79d93368b041f30dd7b3a788f/astro/src/content/quickstarts/quickstart-golang-web.mdx#L185

**Comment by mooreds** [comment]
@alex-fusionauth actually, `content` is for big pieces of content that we want to highlight for the marketing team. Sorry for the confusion. Please remove the `content` label.

**Comment by alex-fusionauth** [comment]
For second issue added https://github.com/FusionAuth/fusionauth-quickstart-golang-web/pull/1
