### ISSUE TITLE
Webhook API docs - Not visually clear what events are entiprise only

### ISSUE THREAD

**Issue by HannahRy** [FusionAuth/fusionauth-site#2376]
https://fusionauth.io/docs/v1/tech/apis/webhooks

Take for example this part of the page:
![image](https://github.com/FusionAuth/fusionauth-site/assets/43540316/e90334d7-cdde-4591-8b14-195bda388132)

Is `user.two-factor.method.remove` the enterprise only event or is `user.update`? When quickly scanning the list, due to spacing it looks like `user.update` is enterprise only, Upon further inspection its can be determined what is correct, but it would be good to make this page more clear. There could be a few options here:

- Correct the vertical spacing
- Use indentation
- Use a symbol
- Separate the enterprise events into its own list.

**Comment by mooreds** [comment]
Thanks for the issue! Appreciate the feedback.

Internal note: we could try playing with the API event list here: site/docs/v1/tech/apis/_event-types.adoc to see what kind of formatting changes are possible.

**Comment by mooreds** [comment]
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2446
