### ISSUE TITLE
/api/login: want to restrict response

### ISSUE THREAD

**Issue by kwehrle** [FusionAuth/fusionauth-site#24]
Hi,
if I use the API to login (POST /api/login, with or without applicationId) I get with the registrations for all applications the user is registerded to. For security reason I want

1. applicationId mandatory for request or without this Id no registrations are send
2. in the response object only the information belonging to this application

An application should not be interested neither if the user is registerd for other applications nor what roles he has in these foreign applications. For us this is a mandatory security feature.

Is there a possibility to configure fusionAuth so this behavior can achieved?

knut

**Comment by kwehrle** [comment]
Sorry :( wrong project. This is an issue for FusionAuth/fusionauth-issues.

**Comment by robotdan** [comment]
Issue moved to fusionauth-issues https://github.com/FusionAuth/fusionauth-issues/issues/357
