### ISSUE TITLE
Fix typo in OIDC vs. SAML article

### ISSUE THREAD

**Issue by bewalt** [FusionAuth/fusionauth-site#2418]
[Link to article](https://fusionauth.io/blog/2023/01/09/saml-and-oidc-difference)

In the section "What is OIDC?" there is a misspelling of FusionAuth. 

[OIDC](https://openid.net/connect/) is an open authentication protocol built on top of the OAuth 2.0 authorization framework. It delegates authentication to identity providers such as Google and **FushionAuth** to verify identities, while defining how an identity provider communicates with a relying party (or the platform providing services) to authenticate an entity (or end user).

**Comment by mooreds** [comment]
Fixed under https://github.com/FusionAuth/fusionauth-site/commit/c8997c9ed7736d8bac7e77d3ab29f0591a879f8e and https://github.com/FusionAuth/fusionauth-site/commit/7c7d8b0f95e6e367c148ec6fde0aa4cebbf7e6ce
