### ISSUE TITLE
Identity Provider Login - API - Complete the Login With AccessToken

### ISSUE THREAD

**Issue by reza-esfandyari** [FusionAuth/fusionauth-site#2507]
referring to this doc: https://fusionauth.io/docs/v1/tech/apis/identity-providers/google#complete-the-google-login

I am  trying to complete a Google login after authenticating a user using the Google API, I have acquired the access_token and it is valid, I tested it with several validation endpoints of Google including the following and they both return correct info 

```
https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={access_token}
https://www.googleapis.com/oauth2/v3/userinfo?access_token={access_token}
```
 but when I am trying to complete the login through FusionAuth by the endpoint **(/api/identity-provider/login)**  it fails, I could capture the logs in the Fusionauth portal and I am attaching them below: 

here is my payload and the endpoint being hit: 

https://[My Domain].fusionauth.io/api/identity-provider/login

```
{
"data": {
    "token": "replace with your access_token"
    },
  "identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46",
  "noLink": false,
  "applicationId": "replace with your application id",
  "noJWT": false
}
```
**FusionAuth API Response**

```
{
    "fieldErrors": {},
    "generalErrors": [
        {
            "code": "[ExternalAuthenticationException]GoogleTokenInfo",
            "message": "A request to the Google Token Info API has failed. Unable to complete this login request."
        }
    ]
}
```` 

**FusionAuth Logs**

![image](https://github.com/FusionAuth/fusionauth-site/assets/9850812/a38b8b02-88da-4e16-8d33-d48c5480eb75)

```
Request to the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint failed.
Status code [400]

Error response is 
{
  "error_description" : "Invalid Value"
}
````

And 

```
Google IdP Response Debug Log [82339786-3dff-42a6-aac6-1f1ceecb6c46]

9/5/2023 09:40:41 PM Z Using token with login method UseRedirect:
9/5/2023 09:40:41 PM Z Call the [https://www.googleapis.com/oauth2/v3/tokeninfo] endpoint.
9/5/2023 09:40:41 PM Z Endpoint returned status code [400]
9/5/2023 09:40:41 PM Z The response was not successful, see the error event log.
````

It seems to me that fusionauth is not passing the access_token as part of the request, I have no visibility but I could mimic that by removing the access token and I got the same error message from Google

**Comment by mooreds** [comment]
Hi @reza-esfandyari what version of FusionAuth are you using?

**Comment by reza-esfandyari** [comment]
hey @mooreds , here is the info, It is hosted by fusionAuth 

```
Version: | 1.42.0
Latest version: | 1.47.1
Nodes: | 1
Instance Id: | d58d59d4-41c6-4bb8-adb1-696475195bda
Runtime mode: | Production
```

**Comment by jobannon** [comment]
@reza-esfandyari Can you confirm that you have completed these steps?  If so, this might be a integration issue or documentation issue rather than an issue with FusionAuth directly.


When completing the login, you will want to pass in the `id_token`.  So this was my sequence from start to finish -- can you confirm if this works for you all well?
 
Steps to complete:

### Get a Code

Notice the scope being used.
 
 ```
https://accounts.google.com/o/oauth2/v2/auth?client_id=<redacted>&redirect_uri=http%3A%2F%2Fsomethingblankfoo.com&response_type=code&scope=openid&state=foo&nonce=foo
```
 
### Call for a token
 
```
curl --request POST \
  --url 'https://oauth2.googleapis.com/token?=' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data client_id=<redacted> \
  --data client_secret= (redacted) \
  --data code=4/0AbUR2VPZuHT80lkUL6kO4(...)A7leG38T51wegCsKZxA \
  --data grant_type=authorization_code \
  --data redirect_uri=http://somethingblankfoo.com \
```

which returns
 
```
{
	"access_token": "ya29.(...)p5FCkoOG5(...)EgqBOxEWPeA0171",
	"expires_in": 3583,
	"scope": "openid",
	"token_type": "Bearer",
	"id_token": "eyJhbGciOiJSUzI1NiIsIm((...)qswf7VfcdsA"
}
```
 
Use the `id_token` to complete the Google Login at FusionAuth
 
```
curl --request POST \
  --url https://local.fusionauth.io/api/identity-provider/login \
  --header 'Content-Type: application/json' \
  --header 'authorization: <api_key>' \
  --data '{
	"applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
	"data": {
		"token": "eyJhbGciOiJSUzI1NiIsIm(...)qswf7VfcdsA"
	},
	"identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46"
}'
```
 
Alternatively, you can call the complete login endpoint with a google auth code only (instead of a token) as such:
 
```
curl --request POST \
  --url https://local.fusionauth.io/api/identity-provider/login \
  --header 'Content-Type: application/json' \
  --header 'authorization:  <api_key>' \
  --data '{
 "applicationId": "85a03867-dccf-4882-adde-1a79aeec50df",
 "data": {
 "code": "4/0AbUR2VMfowiv6WwLYqr78mdf(...)P09J8dcqIfg67ciIyLa2-9erIytIXyw",
 "redirect_uri": "http://somethingblankfoo.com"
 },
 "identityProviderId": "82339786-3dff-42a6-aac6-1f1ceecb6c46"
}'
```

Let us know if this works for you!

**Comment by reza-esfandyari** [comment]
hi @jobannon thanks for looking into it, You are right, the documentation is wrong, it should be token_id for data.token JSON property while it is mentioned access_token by mistake. 

I am not sure if you guys have any other tickets to fix this documentation but I imagine it would apply to the rest of this documentation link (google) as well as other providers. 

Best,

**Comment by mooreds** [comment]
I'll update the doc.

**Comment by mooreds** [comment]
Closing under https://github.com/FusionAuth/fusionauth-site/pull/2513
