### ISSUE TITLE
Newsletter subscribe requires you to enter your email address two times

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#252]
If you are subscribing to the newsletter, the experience is cumbersome. You have to enter your email address twice.

To replicate the issue:

* go to fusionauth.io
* scroll to the bottom
* enter your email address in the newsletter subscription form
* click 'go'
* you are taken to a whole new page
* enter your email address again
* you are subscribed

I'm not sure what is going on because other mailchimp forms work just fine (the whitepaper landing page) without the double entry.

**Comment by voidmain** [comment]
Fixed.
