### ISSUE TITLE
API gateway for cloudflare

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#2520]
Create an API gateway doc for cloudflare. Add it here

https://fusionauth.io/docs/v1/tech/developer-guide/api-gateways/

Here's the basis of the code: https://fusionauth.io/community/forum/topic/2494/how-do-i-verify-a-token-with-the-cloudflare-worker-jwt-library

**Comment by sixhobbits** [comment]
This should be resolved by https://github.com/FusionAuth/fusionauth-site/pull/3099
