### ISSUE TITLE
"Login with..." buttons failure

### ISSUE THREAD

**Issue by olegladyka** [FusionAuth/fusionauth-site#2537]
In FusionAuth version 1.47.1 there is an issue with buttons for "Login with" different identity providers. Clicking on any of these buttons causes error and the login screen is stuck in loading. 

The error: 

> Uncaught TypeError: Cannot read properties of null (reading 'dataset')
>     at Object.captureState (Helper.js?version=1.47.1:40:79)
>     at FusionAuth.IdentityProvider.Redirect._handleLoginClick (Redirect.js?version=1.47.1:42:52)
>     at a.value (PrimeElement.js:1786:29)
>     at a.value (PrimeElement.js:1752:10)
> captureState	@	Helper.js?version=1.47.1:40
> _handleLoginClick	@	Redirect.js?version=1.47.1:42
> value	@	PrimeElement.js:1786
> value	@	PrimeElement.js:1752

**Comment by mooreds** [comment]
Hi @olegladyka ,

Was this a fresh install or an upgrade? If it was an upgrade, from what version?

Thanks.

**Comment by olegladyka** [comment]
Hi @mooreds,

I was upgrading from version 1.46.0, and before that it was upgraded from version 1.43.0

Thanks

**Comment by spwitt** [comment]
Hi @olegladyka

That error is related to a missing `id` on the login button container element. See the **Changed** section of the [1.47.0 release notes](https://fusionauth.io/docs/v1/tech/release-notes#version-1-47-0) for details on how to resolve this.

If you are still having issues, you can ask for help in [FusionAuth's public Slack](https://join.slack.com/t/fusionauth/shared_invite/zt-6ykfov9u-MTwA1A6ptv0Gr6KcFBVG4w) or create a post in the [community forums](https://fusionauth.io/community/forum/).

If you think you have identified a bug in FusionAuth, you can open a bug report in our [GitHub issues repository](https://github.com/FusionAuth/fusionauth-issues/issues/new/choose).
