### ISSUE TITLE
Sample app for entities

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#2539]
Describe/sample app how to use entities for GitHub organization style user permissions.

**Comment by mooreds** [comment]
Being handled here: https://github.com/FusionAuth/fusionauth-site/tree/bpontarelli/organizations

**Comment by mooreds** [comment]
This handles the text, but an example app would still be swell.

**Comment by mooreds** [comment]
@sixhobbits did we ask you to do this? I don't recall.

**Comment by sixhobbits** [comment]
@mooreds yes I think, this looks equivalent to

> please create an example app to go along with this guide: https://fusionauth.io/docs/extend/examples/modeling-organizations . please do it in nodejs. Update the guide to point to code as needed.

**Comment by mooreds** [comment]
Great!

**Comment by sixhobbits** [comment]
This should be resolved by https://github.com/FusionAuth/fusionauth-site/pull/3000
