### ISSUE TITLE
.Net Api Quick Start results in a 404

### ISSUE THREAD

**Issue by CaseyLemieux** [FusionAuth/fusionauth-site#2631]
Browsing to this URL for documentation results in a 404 not found:

https://fusionauth.io/docs/quickstarts/quickstart-dotnet-api

**Comment by mooreds** [comment]
Thanks Casey. We're revising that quickstart and it somehow made it in. Will get that fixed.

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/2632
