### ISSUE TITLE
Tenant External Id updates

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#27]
Missing 
- [x] `deviceCodeTimeToLiveInSeconds`
- [x] `deviceUserCodeIdGenerator`
- [x] Add since flags

Others? Not sure, do a quick audit.

**Comment by smcoll** [comment]
Also `tenant.externalIdentifierConfiguration.externalAuthenticationIdTimeToLiveInSeconds`

**Comment by robotdan** [comment]
@trex when you get a spare minute or two, can you take a look at this one? Should be a quick update.

**Comment by trex** [comment]
Thanks for the catch @smcoll!
