### ISSUE TITLE
Rename email template files

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#2807]
As part of https://github.com/FusionAuth/fusionauth-site/pull/2758, we have all the default template files. 

As part of https://github.com/FusionAuth/fusionauth-issues/issues/2609 we are going to copy them over from the application code on release.

However, the files in fusionauth-site don't match up with the files in the application.

Here are the differences. These are the file names in the application:

```
breached-password.html.ftl
breached-password.txt.ftl
change-password.html.ftl
change-password.txt.ftl
confirm-child.html.ftl
confirm-child.txt.ftl
coppa-email-plus-notice.html.ftl
coppa-email-plus-notice.txt.ftl
two-factor-add.html.ftl
two-factor-add.txt.ftl
two-factor-login.html.ftl
two-factor-login.txt.ftl
two-factor-remove.html.ftl
two-factor-remove.txt.ftl
```

Please update fusionauth-site to read from the correct filename, as well as the template list accessible by wget -i.

For instance, update everything to read from `two-factor-remove.txt.ftl` rather than `two-factor-authentication-method-removed.txt.ftl`

**Comment by Aaron-Ritter** [comment]
@mooreds the templates where named according to the Name field used in the default deployment. There is no other correlation by side the name.

**Comment by mooreds** [comment]
Hmmm. I don't want to deal with a mapping JSON file right now, and don't want to change the default template names in the app.

How about we just use the names of the templates as above, even if they differ slightly from the Name field? They're pretty close.

**Comment by Aaron-Ritter** [comment]
Yes, the earlier comment was more to make sure it is clear that the names will be disconnected from the names used in the UI. My plan was to rename them according to your issue and create a PR. And once completed look in to node cli and come up with a suggestion with the slightly different names.
