### ISSUE TITLE
Document how to integrate with multiple SMTP providers

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#3006]
We already document a few of these: https://fusionauth.io/docs/customize/email-and-messages/configure-email#smtp-providers

But it'd be nice to document a few others.

* resend: https://resend.com/docs/send-with-smtp
* AWS SES
* mailgun
* postmark
* mandrill

**Comment by sixhobbits** [comment]
This should be resolved by https://github.com/FusionAuth/fusionauth-site/pull/3074
