### ISSUE TITLE
FusionAuth.io scrolling broken on mobile

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#305]
To replicate:

* open the mobile site on an android (homepage is fine, but it affects other pages too).
* scroll down
* click on the nav hamburger
* you can't scroll any more. If you've scrolled down far enough, you won't be able to see the nav pop up.

You can work around this by reloading the page.

Tested on chrome and firefox. Note that the docs menu didn't have this issue.

I also see the behavior on ios and safari, though you do get an initial scroll before it locks up

**Comment by voidmain** [comment]
Fixed.
