### ISSUE TITLE
name typo in tenant API

### ISSUE THREAD

**Issue by jegger** [FusionAuth/fusionauth-site#312]
In the documentation you have _tenant.passwordValidationRules.requiredMixedCase_ on page https://fusionauth.io/docs/v1/tech/apis/tenants/ - The correct value is: _tenant.passwordValidationRules.requireMixedCase_ (without the **d**)

**Comment by robotdan** [comment]
Thanks for the catch @jegger !! Fixed. 
https://github.com/FusionAuth/fusionauth-site/commit/bb3c6e0985f638334ec3f80b7a6b87cec3656f05
