### ISSUE TITLE
docs: incorrect parameter listed for Hosted Backend /app/logout/

### ISSUE THREAD

**Issue by peter-greenatlas** [FusionAuth/fusionauth-site#3227]
Hi, this is a minor thing - but since I found it I figured I should report it

I believe the parameter "redirect_uri" shown in the API docs at https://fusionauth.io/docs/apis/hosted-backend#logout should actually be "post_logout_redirect_uri"

I confirmed that "post_logout_redirect_uri" works in my code, and that that is the parameter that the Javascript SDK uses (https://github.com/FusionAuth/fusionauth-javascript-sdk/blob/8a95e97bdb3e49f770e4e0bebd2a1542b67b8727/packages/core/src/UrlHelper/UrlHelper.ts#L56C7-L56C31)

Thanks

**Comment by mooreds** [comment]
Thanks @peter-greenatlas ! We'll take a look.
