### ISSUE TITLE
Validating understanding of docs regarding ID token claims

### ISSUE THREAD

**Issue by smcoll** [FusionAuth/fusionauth-site#33]
i'm not sure whether there is a problem with the documentation per se, but i am surprised at some behavior of FusionAuth based on my comprehension of the documentation, and i'd like to validate my understanding of expected behavior.

First, i'm wanting an ID token with the `applicationId` as a claim, beginning with an unauthenticated user who will be providing their username and password.  Assume the `tenantId` and `applicationId` are known.  It appears that i cannot get such a JWT at `POST /api/login` (with `tenantId` set in a header) since that initial request with username/password in the body call will not be authenticated.  However, with the ID token in the login response, i can make an authenticated `GET /api/jwt/issue?applicationId={applicationId}` to get one.  

_Is that the simplest route possible (two requests)?_

Second, regarding an ID token populate lambda, i have not been able to see the claims transformed in the following cases (having selected the lambda at ~both the tenant and~ the application level):

 - in the token returned by `GET /api/login` with the tenant header set
 - in the token returned by `POST /api/jwt/issue` with the `applicationId` query param set, regardless of whether "JWT" toggle is enabled at the application level.

Default tenant, and default application, initially, but then i created a new application in that tenant and had the same behavior.

_In what case(s) should i see the ID token claims be transformed by a lambda?_  ~Where should i find console logs?  i'm not seeing them in the container stdout for any level (error/info/debug).~ _[EDIT]: i did find a log for a lambda invocation at `/admin/system/event-log/`_

Here is the lambda, as a sanity check:
```js
function populate(jwt, user, registration) {
  jwt.foo = "bar";
}
```

FusionAuth 1.15.4

**Comment by smcoll** [comment]
Still not sure how i got that one lambda log in the first place. i've also made the login and token issue requests mentioned above for a net-new tenant and application (the application having "Id token populate lambda" set to the lambda below), and don't see any new logs regarding the token at `/admin/system/event-log/`.

Lambda contents:

```js
function populate(jwt, user, registration) {
  console.debug("DEBUG"); 
  console.info("INFO"); 
  console.error("ERROR"); 
  jwt.foo = "bar";
}

```

**Comment by robotdan** [comment]
An Id Token is an OpenID Connect concept, so that will not be returned on the Login API. 

The Login API will return a JWT (access token) in the response - so if your lambda is assigned to the Access Token for that application it will be executed during the login request. 

If you do not provide an `applicationId` in the login request body, you will not get the `applicationId` in the JWT body either. 

Are you currently sending in the `applicationId` on the Login request?

**Comment by smcoll** [comment]
Ah, i was assuming the login token was an ID token because it was a JWT - i'm accustomed to opaque access tokens, but of course, JWTs are valid as access tokens.

OK, so i assigned a lambda to "Access token populate lambda" and another to "Id token populate lambda" for my application (it's my understanding that lambdas can only be configured at the application level- not the tenant).

- If i make a login request with a tenant ID, but _without_ an application ID, i get an access token not transformed by the lambda, and see no event logs.
    ```python
    >>> import requests
    >>> url = 'http://fusionauth:9011/api/login'
    >>> tenant_id = '197d4212-683d-4e88-9232-b083c5d86b0d'
    >>> application_id = '1942e00d-b563-4322-a5c9-b2e4857c8796'
    >>> resp = requests.post(url, json={'loginId': 'newuser01@example.com', 'password': 'newuser01'}, headers={'X-FusionAuth-TenantId': tenant_id})
    >>> resp 
    <Response [212]>
    >>> resp.request.headers
    {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-FusionAuth-TenantId': '197d4212-683d-4e88-9232-b083c5d86b0d', 'Content-Length': '61', 'Content-Type': 'application/json'}
    >>> resp.request.body
    b'{"loginId": "newuser01@example.com", "password": "newuser01"}'
    ```
 - If i make a login request with a tenant ID _and_ an application ID, the request returns a 401, which the [docs say](https://fusionauth.io/docs/v1/tech/apis/login#response) mean that the request isn't validated with an API key in the authentication header.  i took that to mean that this won't work as a flow for an unauthenticated user:
    ```python
    >>> resp = requests.post(url, json={'loginId': 'newuser01@example.com', 'password': 'newuser01', 'applicationId': application_id}, headers={'X-FusionAuth-TenantId': tenant_id})
    >>> resp
    <Response [401]>
    ```
    After further thought, i suppose i could make an API key for the SPA with `POST /api/login` permissions, but not sure why that'd be necessary - API keys known by an SPA can't be kept secret.
 - Making that request with the `applicationId` value _and_ the API key in the header is successful, and this does log from the lambda, transform the access token's claims, and include the application ID value:
    ```python
    >>> api_key = '<my-key>'
    >>> resp = requests.post(url, json={'loginId': 'newuser01@example.com', 'password': 'newuser01', 'applicationId': application_id}, headers={'X-FusionAuth-TenantId': tenant_id, 'Authorization': api_key})
    >>> resp
    <Response [212]>
    ```
So i think i understand how lambdas relate to the login endpoint now.

Now on to the ID token endpoint.

- When i make a request to the JWT endpoint, with the new access token in the header, i get an ID token, _but it's transformed by the access token lambda, not the ID token lambda, and the event log confirms this, by naming the access token lambda_:
    ```python
    >>> access_token = resp.json()['token']
    >>> jwt_url = 'http://fusionauth:9011/api/jwt/issue'
    >>> resp = requests.get(jwt_url, data={'applicationId': application_id}, headers={'Authorization': 'Bearer ' + access_token})
    >>> resp
    <Response [200]>
    ```
    This explains why i wasn't able to get the ID token lambda to log in this case- it's the access token lambda which is being used by this endpoint.  FusionAuth 1.15.4.  

Please let me know if i've misunderstood anything.

**Comment by robotdan** [comment]
This all sounds correct. 

- No applicationId, means we don't know which application you're trying to log into, so we can't associate a lambda to call during JWT creation.
- With applicationId, the default configuration is to require an API key, so a 401 is correct. You can disable this requirement in your application configuration. 
- With an applicationId and an API key, correct, only the access token is produced, so the access token lambda is invoked. 
- The JWT issue endpoint is not part of OIDC, so no Id Token, just the access token - so we will invoke the access token lambda if configured.

**Comment by smcoll** [comment]
Ah!  It's all making sense now.  Thanks very much.
