### ISSUE TITLE
FusionAuth Python Client Library

### ISSUE THREAD

**Issue by darkkLUCIFER** [FusionAuth/fusionauth-site#3390]
in website : https://fusionauth.io/docs/sdks/python

there is a small documentaion bug in below line :
 
client_response = client.create_user(None, user_request)

this line is incorrect and should be as below:

client_response = client.create_user(user_request)

**Comment by mooreds** [comment]
Thanks for filing this issue, @darkkLUCIFER .

What version of the python client are you using?

Looking at https://github.com/FusionAuth/fusionauth-python-client/blob/develop/src/main/python/fusionauth/fusionauth_client.py#L601 it looks like you are correct.

**Comment by darkkLUCIFER** [comment]
@mooreds 

fusionauth-client==1.53.0

**Comment by mooreds** [comment]
Awesome. https://github.com/FusionAuth/fusionauth-site/pull/3394 is up for review. Thanks again for letting us know.

**Comment by darkkLUCIFER** [comment]
@mooreds you're welcome

**Comment by mooreds** [comment]
Closed under https://github.com/FusionAuth/fusionauth-site/pull/3394
