### ISSUE TITLE
Documentation: Response body details missing from create theme

### ISSUE THREAD

**Issue by SlothFriend** [FusionAuth/fusionauth-site#34]
The docs for creating a theme (https://fusionauth.io/docs/v1/tech/apis/themes#create-a-theme) don't include details for the response body like all the other api docs.

**Comment by robotdan** [comment]
Thanks for reporting @SlothFriend we'll get that fixed up.

**Comment by mooreds** [comment]
This looks resolved: https://fusionauth.io/docs/v1/tech/apis/themes/#create-a-theme

Closing.
