### ISSUE TITLE
Documentation: User Consent retrieval API

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-site#37]
[Consent API endpoints documentation](https://fusionauth.io/docs/v1/tech/apis/consent#update-a-user-consent) lacks the description of User Consent retrival. I have found out that I can retrieve such information with requests such as
```
GET /api/user/consent/{userConsentId}
```
or with more useful request such as
```
GET /api/user/consent/?userId={userId}
```
Since the behaviour is not documented, one cannot be sure if the API will not be a subject to rapid changes. Also, based only on the documentation, there is no way to retrieve user consent data at all.

**Comment by trex** [comment]
Thanks again for this one @mgetka!
