### ISSUE TITLE
Missing new fields on the SAML v2 IdP for post bindings and signing configuration

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#375]
Update this API - do an audit of the API. 
https://fusionauth.io/docs/v1/tech/apis/identity-providers/samlv2/

Updates from 1.20.0 are missing 
https://fusionauth.io/docs/v1/tech/release-notes/#version-1-20-0

Likely also missing from the UI walk through for this IdP. 
https://fusionauth.io/docs/v1/tech/identity-providers/samlv2/

**Comment by mooreds** [comment]
I believe this is fixed by https://github.com/FusionAuth/fusionauth-site/pull/448 and https://github.com/FusionAuth/fusionauth-site/pull/447

**Comment by robotdan** [comment]
New stuff for https://github.com/FusionAuth/fusionauth-issues/issues/1137 in 1.25.0. 

Affects API doc, SAML v2 IdP doc, same links as above. 

@mooreds I could give this to @jobannon  - thoughts?

**Comment by mooreds** [comment]
I think in a few weeks, this would be a great task for @jobannon !

**Comment by mooreds** [comment]
Closing this out because it is covered in #502 which shipped yesterday.
