### ISSUE TITLE
Documentation: missing isSuperRole for application creation API docs

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-site#39]
"Table 4. Request Body" in [application creation API documentation](https://fusionauth.io/docs/v1/tech/apis/applications#create-an-application) does not contain details on `application.roles[x].isSuperRole` field.

**Comment by trex** [comment]
Thank you for reporting this issue with the docs @mgetka!  I got a change pushed and will roll site this afternoon.
