### ISSUE TITLE
API docs: Invalid HTTP method for update user consent request

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-site#41]
In the [8. Update a User Consent](https://fusionauth.io/docs/v1/tech/apis/consent#update-a-user-consent) API docs, `POST` is listed as one of HTTP methods available for user consents alteration. Based on the expirience with the API, I believe that `PUT` should be mentioned instead of `POST` in this place.

**Comment by robotdan** [comment]
Thanks for reporting @mgetka !

**Comment by mooreds** [comment]
This should be fixed as soon as https://github.com/FusionAuth/fusionauth-site/pull/935 is reviewed and deployed.

**Comment by mooreds** [comment]
This is done.
