### ISSUE TITLE
No JWT lambda selection in Tenant configuration

### ISSUE THREAD

**Issue by smcoll** [FusionAuth/fusionauth-site#42]
https://fusionauth.io/docs/v1/tech/lambdas/jwt-populate says:

> Once a lambda is created, you must assign it to an Application or Tenant. See the JWT tab in the Application and Tenant configuration.

But i don't see any lambda assignment option in the Tenant configuration; only in the Application configuration

v1.15.8

**Comment by robotdan** [comment]
https://fusionauth.io/docs/v1/tech/core-concepts/tenants#jwt

**Comment by mooreds** [comment]
This has been fixed and released.
