### ISSUE TITLE
OpenID Connect: Azure AD

### ISSUE THREAD

**Issue by prateekpandeysuccessive** [FusionAuth/fusionauth-site#43]
I am trying to integrate the Azure AD integration. I followwed the guide that is mentioned here - https://fusionauth.io/docs/v1/tech/identity-providers/openid-connect/azure-ad

I can see "Login with Azure" button on login page. When I do click that:
1. I redirect to the Azure login page.
2. I enter my credentials.
3. I  redirect back automatically to FusionAuth page (at "<fusiont auth domain name>/oauth2/callback") with query strings - `code`, `state` and `session_state`. State query string is having following encoded values:

```
- client_id=<Some Guid>&
- code_challenge=tNh57rNR_z11CoKMGrHyWJiJns2DGCQwcIqAwGelDdE&
- code_challenge_method=S256&
- metaData.device.name=Windows Chrome&
- metaData.device.type=BROWSER&
- nonce=VXZ1NkhYcEczZ0hUWllFc3NQeE44Ql9CZWtmekN4S05CN2VGSlN4aEYxLXF-&
- redirect_uri=<application url>&
- response_mode=&
- response_type=code&
- scope=openid profile offline_access&
- state=VXZ1NkhYcEczZ0hUWllFc3NQeE44Ql9CZWtmekN4S05CN2VGSlN4aEYxLXF-&
- tenantId=<Some GUID>&
- timezone=Asia/Calcutta&
- user_code=&
- identityProviderId=<Some Guid>
```

I get this error redirection (to "<fusiont auth domain name>/oauth2/callback") page:
```
{
  "error" : "invalid_request",
  "error_description" : "The request is missing a required parameter: redirect_uri",
  "error_reason" : "missing_redirect_uri"
}
```

Please assist.

**Comment by robotdan** [comment]
What version of FusionAuth are you running?

**Comment by prateekpandeysuccessive** [comment]
I am using v1.15.6

**Comment by robotdan** [comment]
I believe this is already fixed. Review the release notes, and try upgrading to 1.15.8. 
https://fusionauth.io/docs/v1/tech/release-notes
