### ISSUE TITLE
Broken links in https://fusionauth.io/docs/

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/fusionauth-site#45]
Links inside "Tenants & Apps" are broken.

To automatically handle this in the future, I suggest using a Link Checker service, which will periodically scan your site for broken links. (some services may also provide SEO suggestions, etc.)

**Comment by voidmain** [comment]
@ceefour - I clicked on every link in those docs and none of them appeared broken. Can you point us to the exact page and links that are broken?

We also use a link checker quite frequently and haven't had any broken links lately. If you do find some though, please add them to this with as much detail as possible.

**Comment by ceefour** [comment]
@voidmain Check #46, e.g. this is broken: `https://fusionauth.io/docs/v1/tech/users/groups`

**Comment by voidmain** [comment]
Ah, sorry. I thought you were talking about this page:

https://fusionauth.io/docs/v1/tech/core-concepts/applications

I see the broken links now. Thanks for the PR. We are in the middle of a huge website redesign, so I'm going to actually reject the PR and just fix those on our branch.

**Comment by mooreds** [comment]
Per comments in https://github.com/FusionAuth/fusionauth-site/pull/46 this was fixed in the new design, so we're good.
