### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by mfoitzik** [FusionAuth/fusionauth-site#494]
I am just now going through the 5-minute setup guide. I am setting up on a Windows 10 machine so am following the Windows directions. It would help to specify that you have to be using Power Shell (in contrast to command prompt).

**Comment by jobannon** [comment]
Thanks for the heads up @mfoitzik!  I appreciate you taking the time to offer feedback.  Let us know how the rest of your time is with FusionAuth as you get going 👍🏻
