### ISSUE TITLE
Brave/Chrome do not allow video to view FullScreen

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#518]
# Summary

Tested in both Chrome and Brave (with shields "down") and get the following error (will not allow fullscreen view).
<img width="1312" alt="Screen Shot 2021-03-25 at 11 12 46 AM" src="https://user-images.githubusercontent.com/16090626/112515116-9a961700-8d5b-11eb-9301-279badd4c904.png">

In Safari, fullscreen works as expected.

Unsure if this is an issue with youtube or chrome or other.

**Comment by mooreds** [comment]
What does the console log say?

**Comment by jobannon** [comment]
<img width="914" alt="Screen Shot 2021-03-25 at 5 27 24 PM" src="https://user-images.githubusercontent.com/16090626/112556264-75bb9700-8d8f-11eb-8289-a985e13e237f.png">
<img width="875" alt="Screen Shot 2021-03-25 at 5 27 19 PM" src="https://user-images.githubusercontent.com/16090626/112556276-79e7b480-8d8f-11eb-9573-5eeac5f04f06.png">

**Comment by jobannon** [comment]
Upon page load.
once the video is playing, no additional errors display.

**Comment by robotdan** [comment]
Closing, workaround is to click the YouTube link to open up in a new browser.
