### ISSUE TITLE
Update Screenshots on Advanced Registration Forms

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#595]
# Summary
Some screenshots on advanced registration forms are a bit wonky.  Updates needed.

# Link
https://site-local.fusionauth.io/docs/v1/tech/guides/advanced-registration-forms/#what-are-advanced-registration-forms

**Comment by mooreds** [comment]
I thought the issue was with the UI itself:

https://github.com/FusionAuth/fusionauth-issues/issues/939

Let me know if you don't see the wonkiness :) .

**Comment by jobannon** [comment]
Yeah, I assumed that it was the screenshot/angle/etc.  But yep, looks to be a bug.
