### ISSUE TITLE
Incorrect YouTube embed URL

### ISSUE THREAD

**Issue by elliottcarlson** [FusionAuth/fusionauth-site#611]
On the Advanced Registrations Form, the video embed is pointing to the wrong YouTube ID.

https://github.com/FusionAuth/fusionauth-site/blob/7b1b4e4f518ac63a5875da467042da4e897181d6/site/docs/v1/tech/guides/advanced-registration-forms.adoc#L41

```video::NDXHE8I[youtube,width=560,height=315]```
should be
```video::wte-NDXHE8I[youtube,width=560,height=315]```

**Comment by mooreds** [comment]
Thanks for the report, @elliottcarlson ! This should be deployed today.

Closing.
