### ISSUE TITLE
Self Service Account doc comments

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#636]
https://fusionauth.io/docs/v1/tech/account-management/

- [x] I prefer not to use too much bold text it is distracting in my opinion. The notes about being paid at the top is all bold. We could optionally not make it bold, or add it to a note admonition or something like that. 
- [x] I don't know what we use the term TOTP anywhere in the API or UI, could we use "Authenticator" instead?
- [x] I like all of the screenshots, but for clarify since this is a themed page and a default form we are showing it will very likely not match what people will see except during the initial configuration. If we are all ok with that, then it is fine. 
- [x] We mention User Facing and User facing a lot in this doc. This is good for clarify. This is just my opinion, but adding this to parens in the headings doesn't look clean to me. Could we add it to the text below it, or come up with a visual queue to indicate this is self service or not? Or.. the whole section is really self service so do we need to mention it? 
- [x] This is also very related to themes, but sort of is a separate feature. Perhaps we need a section just for "use workflows". We have password reset, change email, verify registration, verify email, (gated verification coming) which are all related to self service. The heading "Self Service Account Mgmt" is a bit long to fit nicely into our nav.

**Comment by robotdan** [comment]
Can we close this one out?

**Comment by jobannon** [comment]
> Can we close this one out?

Yep, closing.  Opened #661 , #721 , #722 in response to this issue.  I will post in the slack channel tomorrow (but they are just about ready for review 🎉 )
