### ISSUE TITLE
Email Verification API bug field `verification strategy` should `verificationStrategy`

### ISSUE THREAD

**Issue by jobannon** [FusionAuth/fusionauth-site#706]
Should we describe this as the fully qualified field name? `emailConfiguration.verificationStrategy`?

**Comment by jobannon** [comment]
![image](https://user-images.githubusercontent.com/16090626/119603138-d5dbb300-bda9-11eb-97e0-76b973c6b7ea.png)

**Comment by jobannon** [comment]
Like this?

**Comment by robotdan** [comment]
What is the context of this, will it be clear that this is a tenant configuration? Also, is `Form Field` an actual value? I think it is `FormField`  https://github.com/FusionAuth/fusionauth-java-client/blob/67635604429a53a640056b26ade9eee09f5b4253/src/main/java/io/fusionauth/domain/VerificationStrategy.java
