### ISSUE TITLE
JSON Web Tokens and the Login API doc needs updating

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#723]
https://fusionauth.io/docs/v1/tech/tutorials/json-web-tokens/

- broken image
- The Signing key config needs to be updated to call out key master more clearly. The support algorithm doesn't need to be here, it can be part of a key master doc. 
- maybe other things? Needs to be reviewed for accuracy now that that panel has changed some. 

Also, for this page https://fusionauth.io/docs/v1/tech/core-concepts/tenants/#jwt - for the key configuration, we should mention that if you do not see the key type you want, you will want to navigate to Key Master to import, or generate a new key pair for assignment.

**Comment by mooreds** [comment]
See also https://github.com/FusionAuth/fusionauth-site/issues/680

**Comment by mooreds** [comment]
I'm not even sure it is worth updating the tutorial.

**Comment by robotdan** [comment]
If we aren't going to update this, should we delete it?

**Comment by mooreds** [comment]
From #680 

> Suggest either deleting this tutorial or having it be mainly comprised of includes from those other pages so it is up to date without effort.

**Comment by mooreds** [comment]
Delivered under https://github.com/FusionAuth/fusionauth-site/pull/1642
