### ISSUE TITLE
Apache server configuration to be used with Fusion Auth

### ISSUE THREAD

**Issue by paulosobrinho33** [FusionAuth/fusionauth-site#735]
Hello all,

I think that would be very helpful to have a tutorial demonstrating the Apache server configuration for acting as a middleman between a client (ex.: React) and Fusion Auth. Similarly to what was made for the Node / Express.js server at this article https://fusionauth.io/blog/2020/03/10/securely-implement-oauth-in-react/ .

If you agree, please upvote this request.

**Comment by mooreds** [comment]
Hi @paulosobrinho33 ! thanks for using FusionAuth!

I'm not sure how that would work with apache because as far as I know, apache doesn't have a way to catch the authorization code and exchange it for a token (like the node server does). You could of course pair apache with php, perl, or some other language which could do that. Is that what you are looking for?

Thanks!

**Comment by paulosobrinho33** [comment]
Hi @mooreds ,
Thank you for the reply.
Yes, this is what I am looking for. For me, it would be better to have such code in php.
Anyway, with so many applications using OAuth it seems a little strange to me that there isn't something ready for Apache. But my searches have not been successful so far.

**Comment by mooreds** [comment]
@paulosobrinho33 I think thi is what you are looking for: https://github.com/fusionauth/fusionauth-example-php-connector

It's a php app that does the authorization code grant. These files are probably of most interest: 

https://github.com/FusionAuth/fusionauth-example-php-connector/blob/master/oauth-callback.php

https://github.com/FusionAuth/fusionauth-example-php-connector/blob/master/index.php

Does this help?

**Comment by paulosobrinho33** [comment]
Hi @mooreds ,

This is exactly what I was looking for.

Thank you so much.

**Comment by mooreds** [comment]
Excellent. I'll close this issue out, please feel free to re-open.

Also, I'd suggest joining or browsing our forum: https://fusionauth.io/community/forum/ for lots more FusionAuth and OAuth discussions.
