### ISSUE TITLE
Documentation on switching runtime modes?

### ISSUE THREAD

**Issue by trevorr** [FusionAuth/fusionauth-site#737]
This page documents the runtime modes: https://fusionauth.io/docs/v1/tech/installation-guide/fusionauth-app/#runtime-modes

However, it doesn't say whether any special steps need to be taken when changing modes on an existing deployment. I just changed a 2-node AWS ECS deployment from development to production and kept getting errors like this when new production nodes came up:

`ERROR io.fusionauth.api.service.system.NodeService - Node [c98263dc-7f12-4879-93c1-f1a634912a51] cannot be added. The runtime mode is [Development] and this node in [Production] mode.`

Fortunately, terminating the existing development nodes allowed the next pair of production nodes to start okay. However, not knowing to expect this was a little nerve wracking. 😅 I'd propose a paragraph like this:

> All FusionAuth nodes in a multi-node cluster must use the same runtime mode. This means that changing runtime mode of an existing deployment requires stopping all running nodes before starting new nodes with a different runtime mode. Plan for (brief) downtime during this process.

**Comment by robotdan** [comment]
Yes, you are correct. All nodes have to match, we should definitely add this to the doc. Thanks for the suggestion!

**Comment by mooreds** [comment]
@trevorr thanks for submitting the issue. I have a PR out for review which hopefully will help folks encountering this issue in the future: https://github.com/FusionAuth/fusionauth-site/pull/738

**Comment by mooreds** [comment]
Closing, as this PR was merged.
