### ISSUE TITLE
Add new themed page for registration required

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#764]
Add new pages here

Re: https://github.com/FusionAuth/fusionauth-issues/issues/439
Themed doc: https://site-local.fusionauth.io/docs/v1/tech/themes/

**Comment by jobannon** [comment]
@robotdan I think that we have updated all the template variables.

- I added a table of contents for easier navigation (under branch `issue-764-gated-theme`)
- I see there that we have updated a number of the themed pages already, including Email Verification Required and Verify Registration Required (as part of the 1.27 tech preview, I think?)

https://github.com/FusionAuth/fusionauth-site/blob/504ec489fa03b4445c02d6cc7a8c37c9cc27e13f/site/docs/v1/tech/themes/index.adoc#L746)

Let me know if I am misunderstanding something about this issue 🙂
