### ISSUE TITLE
Missing IdP sections for new IdP types for 1.28.0

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#782]
https://fusionauth.io/docs/v1/tech/identity-providers/

- [x]  Xbox 
- [x]  Sony Playstation Network 
- [x]  Epic Games 
- [x]  Twitch 
- [x]  Steam 
- [ ]  Nintendo (pending)

**Comment by robotdan** [comment]
Can we close this one out, or what is left?

**Comment by jobannon** [comment]
This can be closed.  Part of PR #839
