### ISSUE TITLE
Move Link API to the main Identity Provider page?

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#787]
https://fusionauth.io/docs/v1/tech/apis/identity-providers/

Should we move the Link API here? Currently it is under it's own section, but I don't think we have done this anywhere else. If we move it, we need to find all existing links and update them.

**Comment by robotdan** [comment]
This may be ok to leave where it is.. anyone have an opinion?

**Comment by mooreds** [comment]
Sorry, not clear what feedback you are looking for. 

Are you asking "should we move the link API docs into the identity providers index page, or leave it out as a separate document"?

**Comment by robotdan** [comment]
I was thinking we should move the Link API to the this page (https://fusionauth.io/docs/v1/tech/apis/identity-providers/) instead of a sub section. But not sure that makes sense, I may have changed my mind. I can close this for now.
