### ISSUE TITLE
Document RequireRegistration

### ISSUE THREAD

**Issue by MVJosh** [FusionAuth/fusionauth-site#821]
Not sure if this was an accidental omission or if it's currently a work-in-progress, but the `application.oauthConfiguration.requireRegistration` field in `/api/application` doesn't appear to have any documentation currently. 

Please could the docs be updated to include this?

**Comment by mooreds** [comment]
Thanks @MVJosh . We're still working through a backlog of docs, but this is on the list. Sorry about that!

**Comment by MVJosh** [comment]
@mooreds thought that might be the case, just wanted to point it out in case it had been missed.
Thanks for the update! 👍

**Comment by mooreds** [comment]
This is now documented here: https://fusionauth.io/docs/v1/tech/apis/applications/ and https://fusionauth.io/docs/v1/tech/core-concepts/applications/

Closing this issue.
