### ISSUE TITLE
Document `applicationId` on `/api/user/forgot-password`

### ISSUE THREAD

**Issue by voidmain** [FusionAuth/fusionauth-site#834]
It looks like the API docs are missing this parameter, which is used to override the email template that is sent to the user. Here's the doc URL:

https://fusionauth.io/docs/v1/tech/apis/users/#start-forgot-password-workflow

And the request object in the Java client:

https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/java/io/fusionauth/domain/api/user/ForgotPasswordRequest.java

**Comment by mooreds** [comment]
I'm taking this @jobannon :)

**Comment by mooreds** [comment]
I think we have the same issue with the verification email as well. Will audit the other application specific email templates to ensure the docs are up to date.

**Comment by mooreds** [comment]
Looks like a bigger issue with missing application Ids, going to handle in separate GH issues.

**Comment by mooreds** [comment]
Closing, as #850 is merged.
