### ISSUE TITLE
Google And Facebook IdPs are missing change flags in the Login API for the new options

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-site#857]
### Issue

The `data.code` and the `data.redirect_uri` option on the IdP Login API was added in version 1.28.0, but we did not change flag these new fields. 

https://fusionauth.io/docs/v1/tech/apis/identity-providers/google/#complete-the-google-login
https://fusionauth.io/docs/v1/tech/apis/identity-providers/facebook/#complete-the-facebook-login

### Related
https://github.com/FusionAuth/fusionauth-issues/issues/909

**Comment by jobannon** [comment]
I think that this is the only update that is required?

https://github.com/FusionAuth/fusionauth-site/pull/858
