### ISSUE TITLE
No Apple Identity provider API doc

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#89]
There is high level "Sign in with Apple" doc here: https://fusionauth.io/docs/v1/tech/identity-providers/apple

But no corresponding API level documentation page here: https://fusionauth.io/docs/v1/tech/apis/identity-providers/

Unsure if that is intentional.

**Comment by robotdan** [comment]
Still working on doc for this past release

**Comment by mooreds** [comment]
Just got released: https://fusionauth.io/docs/v1/tech/identity-providers/apple
