### ISSUE TITLE
Document that the index template page will always use the default tenant

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-site#927]
The index page (`/`) doesn't, by default, have anything which can be used to pull application or tenant theme information, so unless those are provided as url parameters we use the default tenant theme.

This should be documented in the themes docs and maybe the theme API docs.

**Comment by robotdan** [comment]
The more generic way to say this is - anytime a request is made to a themed page and we are unable to identify the tenant, the default tenant will be used. 

Real life examples:
- Root page `/` when a `client_id` or `tenantId` is not provided. 
- Any themed pages such as `/password/forgot` when a `client_id` is not provided
- Obscure error conditions where we have lost the context for the application or tenant

Related issues:
https://github.com/FusionAuth/fusionauth-issues/issues/378
https://github.com/FusionAuth/fusionauth-issues/issues/994
