### ISSUE TITLE
Missing twoFactorOneTimeCodeIdTimeToLiveInSeconds in tenants Docs

### ISSUE THREAD

**Issue by lucas-av7** [FusionAuth/fusionauth-site#998]
The `twoFactorOneTimeCodeIdTimeToLiveInSeconds` is only mentioned in the JSON body example, we don't have an explanation of what this parameter is for

https://fusionauth.io/docs/v1/tech/apis/tenants/

**Comment by mooreds** [comment]
Thanks for filing this @lucas-av7 . We'll take a look.

**Comment by lucas-av7** [comment]
@mooreds , Thanks! just to be more accurate, it is on API docs

**Comment by mooreds** [comment]
Closing, this should be fixed.

**Comment by mooreds** [comment]
You'll be happy to know @lucas-av7 that I wrote a github action to error when our API client code contains a variable not present on our API docs page. It runs this script: https://github.com/FusionAuth/fusionauth-site/blob/master/src/check-apis-against-client-json.rb 

Hopefully you won't have to file too many more of these types of issues :) .
