### ISSUE TITLE
Missing information about loginConfiguration in Tenants Docs

### ISSUE THREAD

**Issue by lucas-av7** [FusionAuth/fusionauth-site#999]
We only have the example in the JSON, we don't have the details about this parameter 
```json
"loginConfiguration": {
      "requireAuthentication": true
    },
```

**Comment by mooreds** [comment]
Thank you for the bug report @lucas-av7 . We'll get that fixed.

To unblock you, this field is the same as `Require an API key` in the Tenant screen in the admin UI, which is documented here: https://fusionauth.io/docs/v1/tech/core-concepts/tenants/#login-api-settings

**Comment by lucas-av7** [comment]
@mooreds , Thanks! just to be more accurate, it is on API docs

**Comment by mooreds** [comment]
Closing, this is fixed.
